// File automatically generated by wgsl_bindgen^
//
// ^ wgsl_bindgen version 0.21.3
// Changes made to this file will not be saved.
// SourceHash: 3e31c9feb2bbcfa69778569bfa40f55efec3d6c829ea7bba880042345c9df06f

#![allow(unused, non_snake_case, non_camel_case_types, non_upper_case_globals)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ShaderEntry {
    Common,
    Shape,
    Aabb,
    Bvh,
    Integration,
}
impl ShaderEntry {
    pub fn create_pipeline_layout(&self, device: &wgpu::Device) -> wgpu::PipelineLayout {
        match self {
            Self::Common => common::create_pipeline_layout(device),
            Self::Shape => shape::create_pipeline_layout(device),
            Self::Aabb => aabb::create_pipeline_layout(device),
            Self::Bvh => bvh::create_pipeline_layout(device),
            Self::Integration => integration::create_pipeline_layout(device),
        }
    }
    pub fn create_shader_module_embed_source(&self, device: &wgpu::Device) -> wgpu::ShaderModule {
        match self {
            Self::Common => common::create_shader_module_embed_source(device),
            Self::Shape => shape::create_shader_module_embed_source(device),
            Self::Aabb => aabb::create_shader_module_embed_source(device),
            Self::Bvh => bvh::create_shader_module_embed_source(device),
            Self::Integration => integration::create_shader_module_embed_source(device),
        }
    }
}
mod _root {
    pub use super::*;
    pub trait SetBindGroup {
        fn set_bind_group(&mut self, index: u32, bind_group: &wgpu::BindGroup, offsets: &[wgpu::DynamicOffset]);
    }
    impl SetBindGroup for wgpu::RenderPass<'_> {
        fn set_bind_group(&mut self, index: u32, bind_group: &wgpu::BindGroup, offsets: &[wgpu::DynamicOffset]) {
            self.set_bind_group(index, bind_group, offsets);
        }
    }
    impl SetBindGroup for wgpu::RenderBundleEncoder<'_> {
        fn set_bind_group(&mut self, index: u32, bind_group: &wgpu::BindGroup, offsets: &[wgpu::DynamicOffset]) {
            self.set_bind_group(index, bind_group, offsets);
        }
    }
    impl SetBindGroup for wgpu::ComputePass<'_> {
        fn set_bind_group(&mut self, index: u32, bind_group: &wgpu::BindGroup, offsets: &[wgpu::DynamicOffset]) {
            self.set_bind_group(index, bind_group, offsets);
        }
    }
}
pub mod layout_asserts {
    use super::{_root, _root::*};
    const WGSL_BASE_TYPE_ASSERTS: () = {};
    const COMMON_CAMERA_ASSERTS: () = {
        assert!(std::mem::offset_of!(common::Camera, inner) == 0);
        assert!(std::mem::size_of::<common::Camera>() == 64);
    };
    const COMMON_VELOCITY_ASSERTS: () = {
        assert!(std::mem::offset_of!(common::Velocity, inner) == 0);
        assert!(std::mem::size_of::<common::Velocity>() == 8);
    };
    const COMMON_FLAGS_ASSERTS: () = {
        assert!(std::mem::offset_of!(common::Flags, inner) == 0);
        assert!(std::mem::size_of::<common::Flags>() == 4);
    };
    const COMMON_COLOR_ASSERTS: () = {
        assert!(std::mem::offset_of!(common::Color, inner) == 0);
        assert!(std::mem::size_of::<common::Color>() == 16);
    };
    const COMMON_SHAPE_ASSERTS: () = {
        assert!(std::mem::offset_of!(common::Shape, inner) == 0);
        assert!(std::mem::size_of::<common::Shape>() == 4);
    };
    const COMMON_A_A_B_B_ASSERTS: () = {
        assert!(std::mem::offset_of!(common::AABB, min) == 0);
        assert!(std::mem::offset_of!(common::AABB, max) == 8);
        assert!(std::mem::size_of::<common::AABB>() == 16);
    };
    const COMMON_BVH_NODE_ASSERTS: () = {
        assert!(std::mem::offset_of!(common::BvhNode, index) == 0);
        assert!(std::mem::size_of::<common::BvhNode>() == 4);
    };
    const BVH_COMBINE_NODE_PASS_ASSERTS: () = {
        assert!(std::mem::offset_of!(bvh::CombineNodePass, src_start) == 0);
        assert!(std::mem::offset_of!(bvh::CombineNodePass, dst_start) == 4);
        assert!(std::mem::offset_of!(bvh::CombineNodePass, parent_count) == 8);
        assert!(std::mem::size_of::<bvh::CombineNodePass>() == 12);
    };
    const COMMON_MASS_ASSERTS: () = {
        assert!(std::mem::offset_of!(common::Mass, inner) == 0);
        assert!(std::mem::size_of::<common::Mass>() == 4);
    };
    const INTEGRATION_BLACK_HOLE_ASSERTS: () = {
        assert!(std::mem::offset_of!(integration::BlackHole, position) == 0);
        assert!(std::mem::offset_of!(integration::BlackHole, radius) == 8);
        assert!(std::mem::offset_of!(integration::BlackHole, mass) == 12);
        assert!(std::mem::offset_of!(integration::BlackHole, spin) == 16);
        assert!(std::mem::size_of::<integration::BlackHole>() == 24);
    };
}
pub mod common {
    use super::{_root, _root::*};
    pub const FLAG_DRAW_OBJECT: u32 = 1u32;
    pub const FLAG_DRAW_AABB: u32 = 2u32;
    pub const FLAG_PHYSICAL: u32 = 4u32;
    pub const BVH_NODE_TREE_FLAG: u32 = 2147483648u32;
    #[repr(C, align(16))]
    #[derive(Debug, PartialEq, Clone, Copy)]
    pub struct Camera {
        #[doc = "offset: 0, size: 64, type: `mat4x4<f32>`"]
        pub inner: [[f32; 4]; 4],
    }
    impl Camera {
        pub const fn new(inner: [[f32; 4]; 4]) -> Self {
            Self { inner }
        }
    }
    #[repr(C, align(8))]
    #[derive(Debug, PartialEq, Clone, Copy)]
    pub struct Velocity {
        #[doc = "offset: 0, size: 8, type: `vec2<f32>`"]
        pub inner: [f32; 2],
    }
    impl Velocity {
        pub const fn new(inner: [f32; 2]) -> Self {
            Self { inner }
        }
    }
    #[repr(C, align(4))]
    #[derive(Debug, PartialEq, Clone, Copy)]
    pub struct Flags {
        #[doc = "offset: 0, size: 4, type: `u32`"]
        pub inner: u32,
    }
    impl Flags {
        pub const fn new(inner: u32) -> Self {
            Self { inner }
        }
    }
    #[repr(C, align(16))]
    #[derive(Debug, PartialEq, Clone, Copy)]
    pub struct Color {
        #[doc = "offset: 0, size: 16, type: `vec4<f32>`"]
        pub inner: [f32; 4],
    }
    impl Color {
        pub const fn new(inner: [f32; 4]) -> Self {
            Self { inner }
        }
    }
    #[repr(C, align(4))]
    #[derive(Debug, PartialEq, Clone, Copy)]
    pub struct Shape {
        #[doc = "offset: 0, size: 4, type: `u32`"]
        pub inner: u32,
    }
    impl Shape {
        pub const fn new(inner: u32) -> Self {
            Self { inner }
        }
    }
    #[repr(C, align(8))]
    #[derive(Debug, PartialEq, Clone, Copy)]
    pub struct AABB {
        #[doc = "offset: 0, size: 8, type: `vec2<f32>`"]
        pub min: [f32; 2],
        #[doc = "offset: 8, size: 8, type: `vec2<f32>`"]
        pub max: [f32; 2],
    }
    impl AABB {
        pub const fn new(min: [f32; 2], max: [f32; 2]) -> Self {
            Self { min, max }
        }
    }
    #[repr(C, align(4))]
    #[derive(Debug, PartialEq, Clone, Copy)]
    pub struct BvhNode {
        #[doc = "offset: 0, size: 4, type: `u32`"]
        pub index: u32,
    }
    impl BvhNode {
        pub const fn new(index: u32) -> Self {
            Self { index }
        }
    }
    #[repr(C, align(4))]
    #[derive(Debug, PartialEq, Clone, Copy)]
    pub struct Mass {
        #[doc = "offset: 0, size: 4, type: `f32`"]
        pub inner: f32,
    }
    impl Mass {
        pub const fn new(inner: f32) -> Self {
            Self { inner }
        }
    }
    #[derive(Debug)]
    pub struct WgpuPipelineLayout;
    impl WgpuPipelineLayout {
        pub fn bind_group_layout_entries(entries: [wgpu::BindGroupLayout; 0]) -> [wgpu::BindGroupLayout; 0] {
            entries
        }
    }
    pub fn create_pipeline_layout(device: &wgpu::Device) -> wgpu::PipelineLayout {
        device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("Common::PipelineLayout"),
            bind_group_layouts: &[],
            push_constant_ranges: &[],
        })
    }
    pub fn create_shader_module_embed_source(device: &wgpu::Device) -> wgpu::ShaderModule {
        let source = std::borrow::Cow::Borrowed(SHADER_STRING);
        device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("common.wgsl"),
            source: wgpu::ShaderSource::Wgsl(source),
        })
    }
    pub const SHADER_STRING: &str = r#"
struct Camera {
    inner: mat4x4<f32>,
}

struct Velocity {
    inner: vec2<f32>,
}

struct Mass {
    inner: f32,
}

struct Flags {
    inner: u32,
}

struct Color {
    inner: vec4<f32>,
}

struct Shape {
    inner: u32,
}

struct AABB {
    min: vec2<f32>,
    max: vec2<f32>,
}

struct BvhNode {
    index: u32,
}

const UNIT_QUAD_VERTICES: array<vec2<f32>, 6> = array<vec2<f32>, 6>(vec2<f32>(0.5f, 0.5f), vec2<f32>(-0.5f, 0.5f), vec2<f32>(-0.5f, -0.5f), vec2<f32>(-0.5f, -0.5f), vec2<f32>(0.5f, -0.5f), vec2<f32>(0.5f, 0.5f));
const FLAG_DRAW_OBJECT: u32 = 1u;
const FLAG_DRAW_AABB: u32 = 2u;
const FLAG_PHYSICAL: u32 = 4u;
const BVH_NODE_TREE_FLAG: u32 = 2147483648u;

fn invocation_index(gid: vec3<u32>, nwg: vec3<u32>, workgroup_size: u32) -> u32 {
    return (gid.x + ((gid.y * nwg.x) * workgroup_size));
}

"#;
}
pub mod bytemuck_impls {
    use super::{_root, _root::*};
    unsafe impl bytemuck::Zeroable for common::Camera {}
    unsafe impl bytemuck::Pod for common::Camera {}
    unsafe impl bytemuck::Zeroable for common::Velocity {}
    unsafe impl bytemuck::Pod for common::Velocity {}
    unsafe impl bytemuck::Zeroable for common::Flags {}
    unsafe impl bytemuck::Pod for common::Flags {}
    unsafe impl bytemuck::Zeroable for common::Color {}
    unsafe impl bytemuck::Pod for common::Color {}
    unsafe impl bytemuck::Zeroable for common::Shape {}
    unsafe impl bytemuck::Pod for common::Shape {}
    unsafe impl bytemuck::Zeroable for common::AABB {}
    unsafe impl bytemuck::Pod for common::AABB {}
    unsafe impl bytemuck::Zeroable for common::BvhNode {}
    unsafe impl bytemuck::Pod for common::BvhNode {}
    unsafe impl bytemuck::Zeroable for bvh::CombineNodePass {}
    unsafe impl bytemuck::Pod for bvh::CombineNodePass {}
    unsafe impl bytemuck::Zeroable for common::Mass {}
    unsafe impl bytemuck::Pod for common::Mass {}
    unsafe impl bytemuck::Zeroable for integration::BlackHole {}
    unsafe impl bytemuck::Pod for integration::BlackHole {}
}
pub mod shape {
    use super::{_root, _root::*};
    pub const SHAPE_RECT: u32 = 0u32;
    pub const SHAPE_CIRCLE: u32 = 1u32;
    pub const COLORING_SPEED_MIN: f32 = 0f32;
    pub const COLORING_SPEED_MAX: f32 = 4000f32;
    pub const ENTRY_VS_MAIN: &str = "vs_main";
    pub const ENTRY_FS_MAIN: &str = "fs_main";
    #[derive(Debug)]
    pub struct VertexEntry<const N: usize> {
        pub entry_point: &'static str,
        pub buffers: [wgpu::VertexBufferLayout<'static>; N],
        pub constants: Vec<(&'static str, f64)>,
    }
    pub fn vertex_state<'a, const N: usize>(
        module: &'a wgpu::ShaderModule,
        entry: &'a VertexEntry<N>,
    ) -> wgpu::VertexState<'a> {
        wgpu::VertexState {
            module,
            entry_point: Some(entry.entry_point),
            buffers: &entry.buffers,
            compilation_options: wgpu::PipelineCompilationOptions {
                constants: &entry.constants,
                ..Default::default()
            },
        }
    }
    pub fn vs_main_entry() -> VertexEntry<0> {
        VertexEntry {
            entry_point: ENTRY_VS_MAIN,
            buffers: [],
            constants: Default::default(),
        }
    }
    #[derive(Debug)]
    pub struct FragmentEntry<const N: usize> {
        pub entry_point: &'static str,
        pub targets: [Option<wgpu::ColorTargetState>; N],
        pub constants: Vec<(&'static str, f64)>,
    }
    pub fn fragment_state<'a, const N: usize>(
        module: &'a wgpu::ShaderModule,
        entry: &'a FragmentEntry<N>,
    ) -> wgpu::FragmentState<'a> {
        wgpu::FragmentState {
            module,
            entry_point: Some(entry.entry_point),
            targets: &entry.targets,
            compilation_options: wgpu::PipelineCompilationOptions {
                constants: &entry.constants,
                ..Default::default()
            },
        }
    }
    pub fn fs_main_entry(targets: [Option<wgpu::ColorTargetState>; 1]) -> FragmentEntry<1> {
        FragmentEntry {
            entry_point: ENTRY_FS_MAIN,
            targets,
            constants: Default::default(),
        }
    }
    #[derive(Debug)]
    pub struct WgpuBindGroup0EntriesParams<'a> {
        pub camera: wgpu::BufferBinding<'a>,
        pub colors: wgpu::BufferBinding<'a>,
        pub shapes: wgpu::BufferBinding<'a>,
    }
    #[derive(Clone, Debug)]
    pub struct WgpuBindGroup0Entries<'a> {
        pub camera: wgpu::BindGroupEntry<'a>,
        pub colors: wgpu::BindGroupEntry<'a>,
        pub shapes: wgpu::BindGroupEntry<'a>,
    }
    impl<'a> WgpuBindGroup0Entries<'a> {
        pub fn new(params: WgpuBindGroup0EntriesParams<'a>) -> Self {
            Self {
                camera: wgpu::BindGroupEntry {
                    binding: 0,
                    resource: wgpu::BindingResource::Buffer(params.camera),
                },
                colors: wgpu::BindGroupEntry {
                    binding: 1,
                    resource: wgpu::BindingResource::Buffer(params.colors),
                },
                shapes: wgpu::BindGroupEntry {
                    binding: 2,
                    resource: wgpu::BindingResource::Buffer(params.shapes),
                },
            }
        }
        pub fn into_array(self) -> [wgpu::BindGroupEntry<'a>; 3] {
            [self.camera, self.colors, self.shapes]
        }
        pub fn collect<B: FromIterator<wgpu::BindGroupEntry<'a>>>(self) -> B {
            self.into_array().into_iter().collect()
        }
    }
    #[derive(Debug)]
    pub struct WgpuBindGroup0(wgpu::BindGroup);
    impl WgpuBindGroup0 {
        pub const LAYOUT_DESCRIPTOR: wgpu::BindGroupLayoutDescriptor<'static> = wgpu::BindGroupLayoutDescriptor {
            label: Some("Shape::BindGroup0::LayoutDescriptor"),
            entries: &[
                #[doc = " @binding(0): \"camera\""]
                wgpu::BindGroupLayoutEntry {
                    binding: 0,
                    visibility: wgpu::ShaderStages::VERTEX_FRAGMENT,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Uniform,
                        has_dynamic_offset: false,
                        min_binding_size: std::num::NonZeroU64::new(std::mem::size_of::<_root::common::Camera>() as _),
                    },
                    count: None,
                },
                #[doc = " @binding(1): \"colors\""]
                wgpu::BindGroupLayoutEntry {
                    binding: 1,
                    visibility: wgpu::ShaderStages::VERTEX_FRAGMENT,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Storage { read_only: true },
                        has_dynamic_offset: false,
                        min_binding_size: None,
                    },
                    count: None,
                },
                #[doc = " @binding(2): \"shapes\""]
                wgpu::BindGroupLayoutEntry {
                    binding: 2,
                    visibility: wgpu::ShaderStages::VERTEX_FRAGMENT,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Storage { read_only: true },
                        has_dynamic_offset: false,
                        min_binding_size: None,
                    },
                    count: None,
                },
            ],
        };
        pub fn get_bind_group_layout(device: &wgpu::Device) -> wgpu::BindGroupLayout {
            device.create_bind_group_layout(&Self::LAYOUT_DESCRIPTOR)
        }
        pub fn from_bindings(device: &wgpu::Device, bindings: WgpuBindGroup0Entries) -> Self {
            let bind_group_layout = Self::get_bind_group_layout(device);
            let entries = bindings.into_array();
            let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
                label: Some("Shape::BindGroup0"),
                layout: &bind_group_layout,
                entries: &entries,
            });
            Self(bind_group)
        }
        pub fn set(&self, pass: &mut impl SetBindGroup) {
            pass.set_bind_group(0, &self.0, &[]);
        }
    }
    #[derive(Debug)]
    pub struct WgpuBindGroup1EntriesParams<'a> {
        pub flags: wgpu::BufferBinding<'a>,
        pub aabbs: wgpu::BufferBinding<'a>,
        pub velocities: wgpu::BufferBinding<'a>,
    }
    #[derive(Clone, Debug)]
    pub struct WgpuBindGroup1Entries<'a> {
        pub flags: wgpu::BindGroupEntry<'a>,
        pub aabbs: wgpu::BindGroupEntry<'a>,
        pub velocities: wgpu::BindGroupEntry<'a>,
    }
    impl<'a> WgpuBindGroup1Entries<'a> {
        pub fn new(params: WgpuBindGroup1EntriesParams<'a>) -> Self {
            Self {
                flags: wgpu::BindGroupEntry {
                    binding: 0,
                    resource: wgpu::BindingResource::Buffer(params.flags),
                },
                aabbs: wgpu::BindGroupEntry {
                    binding: 1,
                    resource: wgpu::BindingResource::Buffer(params.aabbs),
                },
                velocities: wgpu::BindGroupEntry {
                    binding: 2,
                    resource: wgpu::BindingResource::Buffer(params.velocities),
                },
            }
        }
        pub fn into_array(self) -> [wgpu::BindGroupEntry<'a>; 3] {
            [self.flags, self.aabbs, self.velocities]
        }
        pub fn collect<B: FromIterator<wgpu::BindGroupEntry<'a>>>(self) -> B {
            self.into_array().into_iter().collect()
        }
    }
    #[derive(Debug)]
    pub struct WgpuBindGroup1(wgpu::BindGroup);
    impl WgpuBindGroup1 {
        pub const LAYOUT_DESCRIPTOR: wgpu::BindGroupLayoutDescriptor<'static> = wgpu::BindGroupLayoutDescriptor {
            label: Some("Shape::BindGroup1::LayoutDescriptor"),
            entries: &[
                #[doc = " @binding(0): \"flags\""]
                wgpu::BindGroupLayoutEntry {
                    binding: 0,
                    visibility: wgpu::ShaderStages::VERTEX_FRAGMENT,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Storage { read_only: true },
                        has_dynamic_offset: false,
                        min_binding_size: None,
                    },
                    count: None,
                },
                #[doc = " @binding(1): \"aabbs\""]
                wgpu::BindGroupLayoutEntry {
                    binding: 1,
                    visibility: wgpu::ShaderStages::VERTEX_FRAGMENT,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Storage { read_only: true },
                        has_dynamic_offset: false,
                        min_binding_size: None,
                    },
                    count: None,
                },
                #[doc = " @binding(2): \"velocities\""]
                wgpu::BindGroupLayoutEntry {
                    binding: 2,
                    visibility: wgpu::ShaderStages::VERTEX_FRAGMENT,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Storage { read_only: true },
                        has_dynamic_offset: false,
                        min_binding_size: None,
                    },
                    count: None,
                },
            ],
        };
        pub fn get_bind_group_layout(device: &wgpu::Device) -> wgpu::BindGroupLayout {
            device.create_bind_group_layout(&Self::LAYOUT_DESCRIPTOR)
        }
        pub fn from_bindings(device: &wgpu::Device, bindings: WgpuBindGroup1Entries) -> Self {
            let bind_group_layout = Self::get_bind_group_layout(device);
            let entries = bindings.into_array();
            let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
                label: Some("Shape::BindGroup1"),
                layout: &bind_group_layout,
                entries: &entries,
            });
            Self(bind_group)
        }
        pub fn set(&self, pass: &mut impl SetBindGroup) {
            pass.set_bind_group(1, &self.0, &[]);
        }
    }
    #[doc = " Bind groups can be set individually using their set(render_pass) method, or all at once using `WgpuBindGroups::set`."]
    #[doc = " For optimal performance with many draw calls, it's recommended to organize bindings into bind groups based on update frequency:"]
    #[doc = "   - Bind group 0: Least frequent updates (e.g. per frame resources)"]
    #[doc = "   - Bind group 1: More frequent updates"]
    #[doc = "   - Bind group 2: More frequent updates"]
    #[doc = "   - Bind group 3: Most frequent updates (e.g. per draw resources)"]
    #[derive(Debug, Copy, Clone)]
    pub struct WgpuBindGroups<'a> {
        pub bind_group0: &'a WgpuBindGroup0,
        pub bind_group1: &'a WgpuBindGroup1,
    }
    impl<'a> WgpuBindGroups<'a> {
        pub fn set(&self, pass: &mut impl SetBindGroup) {
            self.bind_group0.set(pass);
            self.bind_group1.set(pass);
        }
    }
    #[derive(Debug)]
    pub struct WgpuPipelineLayout;
    impl WgpuPipelineLayout {
        pub fn bind_group_layout_entries(entries: [wgpu::BindGroupLayout; 2]) -> [wgpu::BindGroupLayout; 2] {
            entries
        }
    }
    pub fn create_pipeline_layout(device: &wgpu::Device) -> wgpu::PipelineLayout {
        device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("Shape::PipelineLayout"),
            bind_group_layouts: &[
                &WgpuBindGroup0::get_bind_group_layout(device),
                &WgpuBindGroup1::get_bind_group_layout(device),
            ],
            push_constant_ranges: &[],
        })
    }
    pub fn create_shader_module_embed_source(device: &wgpu::Device) -> wgpu::ShaderModule {
        let source = std::borrow::Cow::Borrowed(SHADER_STRING);
        device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("shape.wgsl"),
            source: wgpu::ShaderSource::Wgsl(source),
        })
    }
    pub const SHADER_STRING: &str = r#"
struct CameraX_naga_oil_mod_XMNXW23LPNYX {
    inner: mat4x4<f32>,
}

struct VelocityX_naga_oil_mod_XMNXW23LPNYX {
    inner: vec2<f32>,
}

struct FlagsX_naga_oil_mod_XMNXW23LPNYX {
    inner: u32,
}

struct ColorX_naga_oil_mod_XMNXW23LPNYX {
    inner: vec4<f32>,
}

struct ShapeX_naga_oil_mod_XMNXW23LPNYX {
    inner: u32,
}

struct AABBX_naga_oil_mod_XMNXW23LPNYX {
    min: vec2<f32>,
    max: vec2<f32>,
}

struct VertexOutput {
    @builtin(position) clip_position: vec4<f32>,
    @location(0) quad_position: vec2<f32>,
    @location(1) color: vec4<f32>,
    @location(2) @interpolate(flat) shape: u32,
}

struct FragmentOutput {
    @location(0) color: vec4<f32>,
}

const UNIT_QUAD_VERTICESX_naga_oil_mod_XMNXW23LPNYX: array<vec2<f32>, 6> = array<vec2<f32>, 6>(vec2<f32>(0.5f, 0.5f), vec2<f32>(-0.5f, 0.5f), vec2<f32>(-0.5f, -0.5f), vec2<f32>(-0.5f, -0.5f), vec2<f32>(0.5f, -0.5f), vec2<f32>(0.5f, 0.5f));
const FLAG_DRAW_OBJECTX_naga_oil_mod_XMNXW23LPNYX: u32 = 1u;
const FLAG_PHYSICALX_naga_oil_mod_XMNXW23LPNYX: u32 = 4u;
const SHAPE_RECT: u32 = 0u;
const SHAPE_CIRCLE: u32 = 1u;
const COLORING_SPEED_MIN: f32 = 0f;
const COLORING_SPEED_MAX: f32 = 4000f;

@group(0) @binding(0) 
var<uniform> camera: CameraX_naga_oil_mod_XMNXW23LPNYX;
@group(0) @binding(1) 
var<storage> colors: array<ColorX_naga_oil_mod_XMNXW23LPNYX>;
@group(0) @binding(2) 
var<storage> shapes: array<ShapeX_naga_oil_mod_XMNXW23LPNYX>;
@group(1) @binding(0) 
var<storage> flags: array<FlagsX_naga_oil_mod_XMNXW23LPNYX>;
@group(1) @binding(1) 
var<storage> aabbs: array<AABBX_naga_oil_mod_XMNXW23LPNYX>;
@group(1) @binding(2) 
var<storage> velocities: array<VelocityX_naga_oil_mod_XMNXW23LPNYX>;

fn wavelength_to_rgb(lambda: f32) -> vec3<f32> {
    var r: f32 = 0f;
    var g: f32 = 0f;
    var b: f32 = 0f;

    if ((lambda >= 380f) && (lambda < 440f)) {
        r = (-((lambda - 440f)) / 60f);
        b = 1f;
    } else {
        if (lambda < 490f) {
            g = ((lambda - 440f) / 50f);
            b = 1f;
        } else {
            if (lambda < 510f) {
                g = 1f;
                b = (-((lambda - 510f)) / 20f);
            } else {
                if (lambda < 580f) {
                    r = ((lambda - 510f) / 70f);
                    g = 1f;
                } else {
                    if (lambda < 645f) {
                        r = 1f;
                        g = (-((lambda - 645f)) / 65f);
                    } else {
                        if (lambda <= 700f) {
                            r = 1f;
                        }
                    }
                }
            }
        }
    }
    let _e49 = r;
    let _e50 = g;
    let _e51 = b;
    return vec3<f32>(_e49, _e50, _e51);
}

fn spectral_intensity(lambda_1: f32) -> f32 {
    if (lambda_1 < 420f) {
        return (0.3f + ((0.7f * (lambda_1 - 380f)) / 40f));
    }
    if (lambda_1 > 645f) {
        return (0.3f + ((0.7f * (700f - lambda_1)) / 55f));
    }
    return 1f;
}

fn velocity_to_color(velocity: vec2<f32>, relative_speed: f32) -> vec4<f32> {
    let t = clamp(relative_speed, 0f, 1f);
    let lambda_2 = mix(700f, 380f, t);
    let _e7 = wavelength_to_rgb(lambda_2);
    let _e8 = spectral_intensity(lambda_2);
    return vec4<f32>((_e7 * _e8), 0.1f);
}

fn sdf_cirle(p: vec2<f32>) -> f32 {
    return (length(p) - 0.5f);
}

@vertex 
fn vs_main(@builtin(vertex_index) vertex_index: u32, @builtin(instance_index) i: u32) -> VertexOutput {
    var out: VertexOutput = VertexOutput();
    var v: vec2<f32>;
    var scale: vec2<f32>;

    let f = flags[i].inner;
    if ((f & FLAG_DRAW_OBJECTX_naga_oil_mod_XMNXW23LPNYX) == 0u) {
        let _e11 = out;
        return _e11;
    }
    let aabb = aabbs[i];
    let _e18 = velocities[i].inner;
    v = _e18;
    let _e20 = v;
    let relative_speed_1 = clamp((max(0f, (length(_e20) - COLORING_SPEED_MIN)) / COLORING_SPEED_MAX), 0f, 1f);
    if ((f & FLAG_PHYSICALX_naga_oil_mod_XMNXW23LPNYX) == 0u) {
        let _e39 = colors[i].inner;
        out.color = _e39;
    } else {
        let _e41 = v;
        let _e43 = velocity_to_color(_e41, sqrt(relative_speed_1));
        out.color = _e43;
    }
    scale = (aabb.max - aabb.min);
    let center = ((aabb.min + aabb.max) / vec2(2f));
    let _e55 = scale.x;
    let _e57 = scale.y;
    let model = mat4x4<f32>(vec4<f32>(_e55, 0f, 0f, 0f), vec4<f32>(0f, _e57, 0f, 0f), vec4<f32>(0f, 0f, 1f, 0f), vec4<f32>(center.x, center.y, 0f, 1f));
    let vertex = UNIT_QUAD_VERTICESX_naga_oil_mod_XMNXW23LPNYX[vertex_index];
    let _e83 = camera.inner;
    out.clip_position = ((_e83 * model) * vec4<f32>(vertex, 0f, 1f));
    out.quad_position = vertex;
    let _e94 = shapes[i].inner;
    out.shape = _e94;
    let _e95 = out;
    return _e95;
}

@fragment 
fn fs_main(in: VertexOutput) -> FragmentOutput {
    var color: vec4<f32>;

    color = in.color;
    let _e4 = sdf_cirle(in.quad_position);
    let _e5 = fwidth(_e4);
    let w = (_e5 / 2f);
    if (in.shape == SHAPE_CIRCLE) {
        let _e14 = color.w;
        color.w = (_e14 * smoothstep(w, -(w), _e4));
    }
    let _e16 = color;
    return FragmentOutput(_e16);
}
"#;
}
pub mod aabb {
    use super::{_root, _root::*};
    pub const ENTRY_VS_MAIN: &str = "vs_main";
    pub const ENTRY_FS_MAIN: &str = "fs_main";
    #[derive(Debug)]
    pub struct VertexEntry<const N: usize> {
        pub entry_point: &'static str,
        pub buffers: [wgpu::VertexBufferLayout<'static>; N],
        pub constants: Vec<(&'static str, f64)>,
    }
    pub fn vertex_state<'a, const N: usize>(
        module: &'a wgpu::ShaderModule,
        entry: &'a VertexEntry<N>,
    ) -> wgpu::VertexState<'a> {
        wgpu::VertexState {
            module,
            entry_point: Some(entry.entry_point),
            buffers: &entry.buffers,
            compilation_options: wgpu::PipelineCompilationOptions {
                constants: &entry.constants,
                ..Default::default()
            },
        }
    }
    pub fn vs_main_entry() -> VertexEntry<0> {
        VertexEntry {
            entry_point: ENTRY_VS_MAIN,
            buffers: [],
            constants: Default::default(),
        }
    }
    #[derive(Debug)]
    pub struct FragmentEntry<const N: usize> {
        pub entry_point: &'static str,
        pub targets: [Option<wgpu::ColorTargetState>; N],
        pub constants: Vec<(&'static str, f64)>,
    }
    pub fn fragment_state<'a, const N: usize>(
        module: &'a wgpu::ShaderModule,
        entry: &'a FragmentEntry<N>,
    ) -> wgpu::FragmentState<'a> {
        wgpu::FragmentState {
            module,
            entry_point: Some(entry.entry_point),
            targets: &entry.targets,
            compilation_options: wgpu::PipelineCompilationOptions {
                constants: &entry.constants,
                ..Default::default()
            },
        }
    }
    pub fn fs_main_entry(targets: [Option<wgpu::ColorTargetState>; 1]) -> FragmentEntry<1> {
        FragmentEntry {
            entry_point: ENTRY_FS_MAIN,
            targets,
            constants: Default::default(),
        }
    }
    #[derive(Debug)]
    pub struct WgpuBindGroup0EntriesParams<'a> {
        pub camera: wgpu::BufferBinding<'a>,
    }
    #[derive(Clone, Debug)]
    pub struct WgpuBindGroup0Entries<'a> {
        pub camera: wgpu::BindGroupEntry<'a>,
    }
    impl<'a> WgpuBindGroup0Entries<'a> {
        pub fn new(params: WgpuBindGroup0EntriesParams<'a>) -> Self {
            Self {
                camera: wgpu::BindGroupEntry {
                    binding: 0,
                    resource: wgpu::BindingResource::Buffer(params.camera),
                },
            }
        }
        pub fn into_array(self) -> [wgpu::BindGroupEntry<'a>; 1] {
            [self.camera]
        }
        pub fn collect<B: FromIterator<wgpu::BindGroupEntry<'a>>>(self) -> B {
            self.into_array().into_iter().collect()
        }
    }
    #[derive(Debug)]
    pub struct WgpuBindGroup0(wgpu::BindGroup);
    impl WgpuBindGroup0 {
        pub const LAYOUT_DESCRIPTOR: wgpu::BindGroupLayoutDescriptor<'static> = wgpu::BindGroupLayoutDescriptor {
            label: Some("Aabb::BindGroup0::LayoutDescriptor"),
            entries: &[
                #[doc = " @binding(0): \"camera\""]
                wgpu::BindGroupLayoutEntry {
                    binding: 0,
                    visibility: wgpu::ShaderStages::VERTEX_FRAGMENT,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Uniform,
                        has_dynamic_offset: false,
                        min_binding_size: std::num::NonZeroU64::new(std::mem::size_of::<_root::common::Camera>() as _),
                    },
                    count: None,
                },
            ],
        };
        pub fn get_bind_group_layout(device: &wgpu::Device) -> wgpu::BindGroupLayout {
            device.create_bind_group_layout(&Self::LAYOUT_DESCRIPTOR)
        }
        pub fn from_bindings(device: &wgpu::Device, bindings: WgpuBindGroup0Entries) -> Self {
            let bind_group_layout = Self::get_bind_group_layout(device);
            let entries = bindings.into_array();
            let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
                label: Some("Aabb::BindGroup0"),
                layout: &bind_group_layout,
                entries: &entries,
            });
            Self(bind_group)
        }
        pub fn set(&self, pass: &mut impl SetBindGroup) {
            pass.set_bind_group(0, &self.0, &[]);
        }
    }
    #[derive(Debug)]
    pub struct WgpuBindGroup1EntriesParams<'a> {
        pub flags: wgpu::BufferBinding<'a>,
        pub aabbs: wgpu::BufferBinding<'a>,
    }
    #[derive(Clone, Debug)]
    pub struct WgpuBindGroup1Entries<'a> {
        pub flags: wgpu::BindGroupEntry<'a>,
        pub aabbs: wgpu::BindGroupEntry<'a>,
    }
    impl<'a> WgpuBindGroup1Entries<'a> {
        pub fn new(params: WgpuBindGroup1EntriesParams<'a>) -> Self {
            Self {
                flags: wgpu::BindGroupEntry {
                    binding: 0,
                    resource: wgpu::BindingResource::Buffer(params.flags),
                },
                aabbs: wgpu::BindGroupEntry {
                    binding: 1,
                    resource: wgpu::BindingResource::Buffer(params.aabbs),
                },
            }
        }
        pub fn into_array(self) -> [wgpu::BindGroupEntry<'a>; 2] {
            [self.flags, self.aabbs]
        }
        pub fn collect<B: FromIterator<wgpu::BindGroupEntry<'a>>>(self) -> B {
            self.into_array().into_iter().collect()
        }
    }
    #[derive(Debug)]
    pub struct WgpuBindGroup1(wgpu::BindGroup);
    impl WgpuBindGroup1 {
        pub const LAYOUT_DESCRIPTOR: wgpu::BindGroupLayoutDescriptor<'static> = wgpu::BindGroupLayoutDescriptor {
            label: Some("Aabb::BindGroup1::LayoutDescriptor"),
            entries: &[
                #[doc = " @binding(0): \"flags\""]
                wgpu::BindGroupLayoutEntry {
                    binding: 0,
                    visibility: wgpu::ShaderStages::VERTEX_FRAGMENT,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Storage { read_only: true },
                        has_dynamic_offset: false,
                        min_binding_size: None,
                    },
                    count: None,
                },
                #[doc = " @binding(1): \"aabbs\""]
                wgpu::BindGroupLayoutEntry {
                    binding: 1,
                    visibility: wgpu::ShaderStages::VERTEX_FRAGMENT,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Storage { read_only: true },
                        has_dynamic_offset: false,
                        min_binding_size: None,
                    },
                    count: None,
                },
            ],
        };
        pub fn get_bind_group_layout(device: &wgpu::Device) -> wgpu::BindGroupLayout {
            device.create_bind_group_layout(&Self::LAYOUT_DESCRIPTOR)
        }
        pub fn from_bindings(device: &wgpu::Device, bindings: WgpuBindGroup1Entries) -> Self {
            let bind_group_layout = Self::get_bind_group_layout(device);
            let entries = bindings.into_array();
            let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
                label: Some("Aabb::BindGroup1"),
                layout: &bind_group_layout,
                entries: &entries,
            });
            Self(bind_group)
        }
        pub fn set(&self, pass: &mut impl SetBindGroup) {
            pass.set_bind_group(1, &self.0, &[]);
        }
    }
    #[doc = " Bind groups can be set individually using their set(render_pass) method, or all at once using `WgpuBindGroups::set`."]
    #[doc = " For optimal performance with many draw calls, it's recommended to organize bindings into bind groups based on update frequency:"]
    #[doc = "   - Bind group 0: Least frequent updates (e.g. per frame resources)"]
    #[doc = "   - Bind group 1: More frequent updates"]
    #[doc = "   - Bind group 2: More frequent updates"]
    #[doc = "   - Bind group 3: Most frequent updates (e.g. per draw resources)"]
    #[derive(Debug, Copy, Clone)]
    pub struct WgpuBindGroups<'a> {
        pub bind_group0: &'a WgpuBindGroup0,
        pub bind_group1: &'a WgpuBindGroup1,
    }
    impl<'a> WgpuBindGroups<'a> {
        pub fn set(&self, pass: &mut impl SetBindGroup) {
            self.bind_group0.set(pass);
            self.bind_group1.set(pass);
        }
    }
    #[derive(Debug)]
    pub struct WgpuPipelineLayout;
    impl WgpuPipelineLayout {
        pub fn bind_group_layout_entries(entries: [wgpu::BindGroupLayout; 2]) -> [wgpu::BindGroupLayout; 2] {
            entries
        }
    }
    pub fn create_pipeline_layout(device: &wgpu::Device) -> wgpu::PipelineLayout {
        device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("Aabb::PipelineLayout"),
            bind_group_layouts: &[
                &WgpuBindGroup0::get_bind_group_layout(device),
                &WgpuBindGroup1::get_bind_group_layout(device),
            ],
            push_constant_ranges: &[],
        })
    }
    pub fn create_shader_module_embed_source(device: &wgpu::Device) -> wgpu::ShaderModule {
        let source = std::borrow::Cow::Borrowed(SHADER_STRING);
        device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("aabb.wgsl"),
            source: wgpu::ShaderSource::Wgsl(source),
        })
    }
    pub const SHADER_STRING: &str = r#"
struct CameraX_naga_oil_mod_XMNXW23LPNYX {
    inner: mat4x4<f32>,
}

struct FlagsX_naga_oil_mod_XMNXW23LPNYX {
    inner: u32,
}

struct AABBX_naga_oil_mod_XMNXW23LPNYX {
    min: vec2<f32>,
    max: vec2<f32>,
}

struct VertexOutput {
    @builtin(position) clip_position: vec4<f32>,
    @location(0) @interpolate(flat) flags: u32,
    @location(1) scale: f32,
    @location(2) quad_position: vec2<f32>,
}

struct FragmentOutput {
    @location(0) color: vec4<f32>,
}

const FLAG_DRAW_AABBX_naga_oil_mod_XMNXW23LPNYX: u32 = 2u;
const UNIT_QUAD_VERTICES: array<vec2<f32>, 5> = array<vec2<f32>, 5>(vec2<f32>(0.5f, 0.5f), vec2<f32>(-0.5f, 0.5f), vec2<f32>(-0.5f, -0.5f), vec2<f32>(0.5f, -0.5f), vec2<f32>(0.5f, 0.5f));

@group(0) @binding(0) 
var<uniform> camera: CameraX_naga_oil_mod_XMNXW23LPNYX;
@group(1) @binding(0) 
var<storage> flags_1: array<FlagsX_naga_oil_mod_XMNXW23LPNYX>;
@group(1) @binding(1) 
var<storage> aabbs: array<AABBX_naga_oil_mod_XMNXW23LPNYX>;

@vertex 
fn vs_main(@builtin(vertex_index) vertex_index: u32, @builtin(instance_index) i: u32) -> VertexOutput {
    var out: VertexOutput = VertexOutput();
    var flags: u32 = FLAG_DRAW_AABBX_naga_oil_mod_XMNXW23LPNYX;

    if (i < arrayLength((&flags_1))) {
        let _e9 = flags_1[i].inner;
        flags = _e9;
        let _e11 = flags;
        if ((_e11 & FLAG_DRAW_AABBX_naga_oil_mod_XMNXW23LPNYX) == 0u) {
            let _e17 = out;
            return _e17;
        }
    }
    let aabb = aabbs[i];
    let scale = (aabb.max - aabb.min);
    let center = ((aabb.min + aabb.max) / vec2(2f));
    let model = mat4x4<f32>(vec4<f32>(scale.x, 0f, 0f, 0f), vec4<f32>(0f, scale.y, 0f, 0f), vec4<f32>(0f, 0f, 1f, 0f), vec4<f32>(center.x, center.y, 0f, 1f));
    let vertex = UNIT_QUAD_VERTICES[vertex_index];
    let _e57 = camera.inner;
    out.clip_position = ((_e57 * model) * vec4<f32>(vertex, 0f, 1f));
    let _e64 = flags;
    out.flags = _e64;
    out.scale = max(scale.x, scale.y);
    out.quad_position = vertex;
    let _e70 = out;
    return _e70;
}

@fragment 
fn fs_main(in: VertexOutput) -> FragmentOutput {
    if ((in.flags & FLAG_DRAW_AABBX_naga_oil_mod_XMNXW23LPNYX) == 0u) {
        discard;
    }
    let intensity = min(1f, (length(in.scale) / 2000f));
    return FragmentOutput(vec4<f32>(intensity, intensity, intensity, intensity));
}
"#;
}
pub mod bvh {
    use super::{_root, _root::*};
    #[repr(C, align(4))]
    #[derive(Debug, PartialEq, Clone, Copy)]
    pub struct CombineNodePass {
        #[doc = "offset: 0, size: 4, type: `u32`"]
        pub src_start: u32,
        #[doc = "offset: 4, size: 4, type: `u32`"]
        pub dst_start: u32,
        #[doc = "offset: 8, size: 4, type: `u32`"]
        pub parent_count: u32,
    }
    impl CombineNodePass {
        pub const fn new(src_start: u32, dst_start: u32, parent_count: u32) -> Self {
            Self {
                src_start,
                dst_start,
                parent_count,
            }
        }
    }
    pub const WORKGROUP_SIZE: u32 = 64u32;
    pub mod compute {
        use super::{_root, _root::*};
        pub const COMBINE_NODES_WORKGROUP_SIZE: [u32; 3] = [64, 1, 1];
        pub fn create_combine_nodes_pipeline_embed_source(device: &wgpu::Device) -> wgpu::ComputePipeline {
            let module = super::create_shader_module_embed_source(device);
            let layout = super::create_pipeline_layout(device);
            device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
                label: Some("Compute Pipeline combine_nodes"),
                layout: Some(&layout),
                module: &module,
                entry_point: Some("combine_nodes"),
                compilation_options: Default::default(),
                cache: None,
            })
        }
    }
    pub const ENTRY_COMBINE_NODES: &str = "combine_nodes";
    #[derive(Debug)]
    pub struct WgpuBindGroup0EntriesParams<'a> {
        pub nodes: wgpu::BufferBinding<'a>,
    }
    #[derive(Clone, Debug)]
    pub struct WgpuBindGroup0Entries<'a> {
        pub nodes: wgpu::BindGroupEntry<'a>,
    }
    impl<'a> WgpuBindGroup0Entries<'a> {
        pub fn new(params: WgpuBindGroup0EntriesParams<'a>) -> Self {
            Self {
                nodes: wgpu::BindGroupEntry {
                    binding: 0,
                    resource: wgpu::BindingResource::Buffer(params.nodes),
                },
            }
        }
        pub fn into_array(self) -> [wgpu::BindGroupEntry<'a>; 1] {
            [self.nodes]
        }
        pub fn collect<B: FromIterator<wgpu::BindGroupEntry<'a>>>(self) -> B {
            self.into_array().into_iter().collect()
        }
    }
    #[derive(Debug)]
    pub struct WgpuBindGroup0(wgpu::BindGroup);
    impl WgpuBindGroup0 {
        pub const LAYOUT_DESCRIPTOR: wgpu::BindGroupLayoutDescriptor<'static> = wgpu::BindGroupLayoutDescriptor {
            label: Some("Bvh::BindGroup0::LayoutDescriptor"),
            entries: &[
                #[doc = " @binding(0): \"nodes\""]
                wgpu::BindGroupLayoutEntry {
                    binding: 0,
                    visibility: wgpu::ShaderStages::COMPUTE,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Storage { read_only: false },
                        has_dynamic_offset: false,
                        min_binding_size: None,
                    },
                    count: None,
                },
            ],
        };
        pub fn get_bind_group_layout(device: &wgpu::Device) -> wgpu::BindGroupLayout {
            device.create_bind_group_layout(&Self::LAYOUT_DESCRIPTOR)
        }
        pub fn from_bindings(device: &wgpu::Device, bindings: WgpuBindGroup0Entries) -> Self {
            let bind_group_layout = Self::get_bind_group_layout(device);
            let entries = bindings.into_array();
            let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
                label: Some("Bvh::BindGroup0"),
                layout: &bind_group_layout,
                entries: &entries,
            });
            Self(bind_group)
        }
        pub fn set(&self, pass: &mut impl SetBindGroup) {
            pass.set_bind_group(0, &self.0, &[]);
        }
    }
    #[derive(Debug)]
    pub struct WgpuBindGroup1EntriesParams<'a> {
        pub aabbs: wgpu::BufferBinding<'a>,
    }
    #[derive(Clone, Debug)]
    pub struct WgpuBindGroup1Entries<'a> {
        pub aabbs: wgpu::BindGroupEntry<'a>,
    }
    impl<'a> WgpuBindGroup1Entries<'a> {
        pub fn new(params: WgpuBindGroup1EntriesParams<'a>) -> Self {
            Self {
                aabbs: wgpu::BindGroupEntry {
                    binding: 0,
                    resource: wgpu::BindingResource::Buffer(params.aabbs),
                },
            }
        }
        pub fn into_array(self) -> [wgpu::BindGroupEntry<'a>; 1] {
            [self.aabbs]
        }
        pub fn collect<B: FromIterator<wgpu::BindGroupEntry<'a>>>(self) -> B {
            self.into_array().into_iter().collect()
        }
    }
    #[derive(Debug)]
    pub struct WgpuBindGroup1(wgpu::BindGroup);
    impl WgpuBindGroup1 {
        pub const LAYOUT_DESCRIPTOR: wgpu::BindGroupLayoutDescriptor<'static> = wgpu::BindGroupLayoutDescriptor {
            label: Some("Bvh::BindGroup1::LayoutDescriptor"),
            entries: &[
                #[doc = " @binding(0): \"aabbs\""]
                wgpu::BindGroupLayoutEntry {
                    binding: 0,
                    visibility: wgpu::ShaderStages::COMPUTE,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Storage { read_only: false },
                        has_dynamic_offset: false,
                        min_binding_size: None,
                    },
                    count: None,
                },
            ],
        };
        pub fn get_bind_group_layout(device: &wgpu::Device) -> wgpu::BindGroupLayout {
            device.create_bind_group_layout(&Self::LAYOUT_DESCRIPTOR)
        }
        pub fn from_bindings(device: &wgpu::Device, bindings: WgpuBindGroup1Entries) -> Self {
            let bind_group_layout = Self::get_bind_group_layout(device);
            let entries = bindings.into_array();
            let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
                label: Some("Bvh::BindGroup1"),
                layout: &bind_group_layout,
                entries: &entries,
            });
            Self(bind_group)
        }
        pub fn set(&self, pass: &mut impl SetBindGroup) {
            pass.set_bind_group(1, &self.0, &[]);
        }
    }
    #[doc = " Bind groups can be set individually using their set(render_pass) method, or all at once using `WgpuBindGroups::set`."]
    #[doc = " For optimal performance with many draw calls, it's recommended to organize bindings into bind groups based on update frequency:"]
    #[doc = "   - Bind group 0: Least frequent updates (e.g. per frame resources)"]
    #[doc = "   - Bind group 1: More frequent updates"]
    #[doc = "   - Bind group 2: More frequent updates"]
    #[doc = "   - Bind group 3: Most frequent updates (e.g. per draw resources)"]
    #[derive(Debug, Copy, Clone)]
    pub struct WgpuBindGroups<'a> {
        pub bind_group0: &'a WgpuBindGroup0,
        pub bind_group1: &'a WgpuBindGroup1,
    }
    impl<'a> WgpuBindGroups<'a> {
        pub fn set(&self, pass: &mut impl SetBindGroup) {
            self.bind_group0.set(pass);
            self.bind_group1.set(pass);
        }
    }
    #[derive(Debug)]
    pub struct WgpuPipelineLayout;
    impl WgpuPipelineLayout {
        pub fn bind_group_layout_entries(entries: [wgpu::BindGroupLayout; 2]) -> [wgpu::BindGroupLayout; 2] {
            entries
        }
    }
    pub fn create_pipeline_layout(device: &wgpu::Device) -> wgpu::PipelineLayout {
        device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("Bvh::PipelineLayout"),
            bind_group_layouts: &[
                &WgpuBindGroup0::get_bind_group_layout(device),
                &WgpuBindGroup1::get_bind_group_layout(device),
            ],
            push_constant_ranges: &[wgpu::PushConstantRange {
                stages: wgpu::ShaderStages::COMPUTE,
                range: 0..12,
            }],
        })
    }
    pub fn create_shader_module_embed_source(device: &wgpu::Device) -> wgpu::ShaderModule {
        let source = std::borrow::Cow::Borrowed(SHADER_STRING);
        device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("bvh.wgsl"),
            source: wgpu::ShaderSource::Wgsl(source),
        })
    }
    pub const SHADER_STRING: &str = r#"
struct AABBX_naga_oil_mod_XMNXW23LPNYX {
    min: vec2<f32>,
    max: vec2<f32>,
}

struct BvhNodeX_naga_oil_mod_XMNXW23LPNYX {
    index: u32,
}

struct CombineNodePass {
    src_start: u32,
    dst_start: u32,
    parent_count: u32,
}

const BVH_NODE_TREE_FLAGX_naga_oil_mod_XMNXW23LPNYX: u32 = 2147483648u;
const WORKGROUP_SIZE: u32 = 64u;

var<push_constant> params: CombineNodePass;
@group(0) @binding(0) 
var<storage, read_write> nodes: array<BvhNodeX_naga_oil_mod_XMNXW23LPNYX>;
@group(1) @binding(0) 
var<storage, read_write> aabbs: array<AABBX_naga_oil_mod_XMNXW23LPNYX>;

fn invocation_indexX_naga_oil_mod_XMNXW23LPNYX(gid_1: vec3<u32>, nwg_1: vec3<u32>, workgroup_size: u32) -> u32 {
    return (gid_1.x + ((gid_1.y * nwg_1.x) * workgroup_size));
}

@compute @workgroup_size(64, 1, 1) 
fn combine_nodes(@builtin(global_invocation_id) gid: vec3<u32>, @builtin(num_workgroups) nwg: vec3<u32>) {
    let _e3 = invocation_indexX_naga_oil_mod_XMNXW23LPNYX(gid, nwg, WORKGROUP_SIZE);
    let _e6 = params.parent_count;
    if (_e3 >= _e6) {
        return;
    }
    let _e10 = params.src_start;
    let src = (_e10 + (_e3 * 2u));
    let _e16 = params.dst_start;
    let dst = (_e16 + _e3);
    nodes[dst] = BvhNodeX_naga_oil_mod_XMNXW23LPNYX((src | BVH_NODE_TREE_FLAGX_naga_oil_mod_XMNXW23LPNYX));
    let left_aabb = aabbs[src];
    let right_aabb = aabbs[(src + 1u)];
    let aabb_min = min(left_aabb.min, right_aabb.min);
    let aabb_max = max(left_aabb.max, right_aabb.max);
    aabbs[dst] = AABBX_naga_oil_mod_XMNXW23LPNYX(aabb_min, aabb_max);
    return;
}
"#;
}
pub mod integration {
    use super::{_root, _root::*};
    #[repr(C, align(8))]
    #[derive(Debug, PartialEq, Clone, Copy)]
    pub struct BlackHole {
        #[doc = "offset: 0, size: 8, type: `vec2<f32>`"]
        pub position: [f32; 2],
        #[doc = "offset: 8, size: 4, type: `f32`"]
        pub radius: f32,
        #[doc = "offset: 12, size: 4, type: `f32`"]
        pub mass: f32,
        #[doc = "offset: 16, size: 4, type: `f32`"]
        pub spin: f32,
        pub _pad_spin: [u8; 0x4],
    }
    impl BlackHole {
        pub const fn new(position: [f32; 2], radius: f32, mass: f32, spin: f32) -> Self {
            Self {
                position,
                radius,
                mass,
                spin,
                _pad_spin: [0; 0x4],
            }
        }
    }
    #[repr(C)]
    #[derive(Debug, PartialEq, Clone, Copy)]
    pub struct BlackHoleInit {
        pub position: [f32; 2],
        pub radius: f32,
        pub mass: f32,
        pub spin: f32,
    }
    impl BlackHoleInit {
        pub fn build(&self) -> BlackHole {
            BlackHole {
                position: self.position,
                radius: self.radius,
                mass: self.mass,
                spin: self.spin,
                _pad_spin: [0; 0x4],
            }
        }
    }
    impl From<BlackHoleInit> for BlackHole {
        fn from(data: BlackHoleInit) -> Self {
            data.build()
        }
    }
    pub const WORKGROUP_SIZE: u32 = 64u32;
    pub const STIFFNESS: f32 = 1000000f32;
    pub const RESTITUTION: f32 = 0.85f32;
    pub const GAMMA_COEFF: f32 = 186.15263f32;
    pub mod compute {
        use super::{_root, _root::*};
        pub const INTEGRATE_WORKGROUP_SIZE: [u32; 3] = [64, 1, 1];
        pub fn create_integrate_pipeline_embed_source(device: &wgpu::Device) -> wgpu::ComputePipeline {
            let module = super::create_shader_module_embed_source(device);
            let layout = super::create_pipeline_layout(device);
            device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
                label: Some("Compute Pipeline integrate"),
                layout: Some(&layout),
                module: &module,
                entry_point: Some("integrate"),
                compilation_options: Default::default(),
                cache: None,
            })
        }
    }
    pub const ENTRY_INTEGRATE: &str = "integrate";
    #[derive(Debug)]
    pub struct WgpuBindGroup0EntriesParams<'a> {
        pub dt: wgpu::BufferBinding<'a>,
        pub gravitational_constant: wgpu::BufferBinding<'a>,
        pub global_force: wgpu::BufferBinding<'a>,
        pub masses: wgpu::BufferBinding<'a>,
        pub nodes: wgpu::BufferBinding<'a>,
    }
    #[derive(Clone, Debug)]
    pub struct WgpuBindGroup0Entries<'a> {
        pub dt: wgpu::BindGroupEntry<'a>,
        pub gravitational_constant: wgpu::BindGroupEntry<'a>,
        pub global_force: wgpu::BindGroupEntry<'a>,
        pub masses: wgpu::BindGroupEntry<'a>,
        pub nodes: wgpu::BindGroupEntry<'a>,
    }
    impl<'a> WgpuBindGroup0Entries<'a> {
        pub fn new(params: WgpuBindGroup0EntriesParams<'a>) -> Self {
            Self {
                dt: wgpu::BindGroupEntry {
                    binding: 0,
                    resource: wgpu::BindingResource::Buffer(params.dt),
                },
                gravitational_constant: wgpu::BindGroupEntry {
                    binding: 1,
                    resource: wgpu::BindingResource::Buffer(params.gravitational_constant),
                },
                global_force: wgpu::BindGroupEntry {
                    binding: 2,
                    resource: wgpu::BindingResource::Buffer(params.global_force),
                },
                masses: wgpu::BindGroupEntry {
                    binding: 3,
                    resource: wgpu::BindingResource::Buffer(params.masses),
                },
                nodes: wgpu::BindGroupEntry {
                    binding: 4,
                    resource: wgpu::BindingResource::Buffer(params.nodes),
                },
            }
        }
        pub fn into_array(self) -> [wgpu::BindGroupEntry<'a>; 5] {
            [
                self.dt,
                self.gravitational_constant,
                self.global_force,
                self.masses,
                self.nodes,
            ]
        }
        pub fn collect<B: FromIterator<wgpu::BindGroupEntry<'a>>>(self) -> B {
            self.into_array().into_iter().collect()
        }
    }
    #[derive(Debug)]
    pub struct WgpuBindGroup0(wgpu::BindGroup);
    impl WgpuBindGroup0 {
        pub const LAYOUT_DESCRIPTOR: wgpu::BindGroupLayoutDescriptor<'static> = wgpu::BindGroupLayoutDescriptor {
            label: Some("Integration::BindGroup0::LayoutDescriptor"),
            entries: &[
                #[doc = " @binding(0): \"dt\""]
                wgpu::BindGroupLayoutEntry {
                    binding: 0,
                    visibility: wgpu::ShaderStages::COMPUTE,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Uniform,
                        has_dynamic_offset: false,
                        min_binding_size: std::num::NonZeroU64::new(std::mem::size_of::<f32>() as _),
                    },
                    count: None,
                },
                #[doc = " @binding(1): \"gravitational_constant\""]
                wgpu::BindGroupLayoutEntry {
                    binding: 1,
                    visibility: wgpu::ShaderStages::COMPUTE,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Uniform,
                        has_dynamic_offset: false,
                        min_binding_size: std::num::NonZeroU64::new(std::mem::size_of::<f32>() as _),
                    },
                    count: None,
                },
                #[doc = " @binding(2): \"global_force\""]
                wgpu::BindGroupLayoutEntry {
                    binding: 2,
                    visibility: wgpu::ShaderStages::COMPUTE,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Uniform,
                        has_dynamic_offset: false,
                        min_binding_size: std::num::NonZeroU64::new(std::mem::size_of::<[f32; 2]>() as _),
                    },
                    count: None,
                },
                #[doc = " @binding(3): \"masses\""]
                wgpu::BindGroupLayoutEntry {
                    binding: 3,
                    visibility: wgpu::ShaderStages::COMPUTE,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Storage { read_only: true },
                        has_dynamic_offset: false,
                        min_binding_size: None,
                    },
                    count: None,
                },
                #[doc = " @binding(4): \"nodes\""]
                wgpu::BindGroupLayoutEntry {
                    binding: 4,
                    visibility: wgpu::ShaderStages::COMPUTE,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Storage { read_only: true },
                        has_dynamic_offset: false,
                        min_binding_size: None,
                    },
                    count: None,
                },
            ],
        };
        pub fn get_bind_group_layout(device: &wgpu::Device) -> wgpu::BindGroupLayout {
            device.create_bind_group_layout(&Self::LAYOUT_DESCRIPTOR)
        }
        pub fn from_bindings(device: &wgpu::Device, bindings: WgpuBindGroup0Entries) -> Self {
            let bind_group_layout = Self::get_bind_group_layout(device);
            let entries = bindings.into_array();
            let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
                label: Some("Integration::BindGroup0"),
                layout: &bind_group_layout,
                entries: &entries,
            });
            Self(bind_group)
        }
        pub fn set(&self, pass: &mut impl SetBindGroup) {
            pass.set_bind_group(0, &self.0, &[]);
        }
    }
    #[derive(Debug)]
    pub struct WgpuBindGroup1EntriesParams<'a> {
        pub blackhole_count: wgpu::BufferBinding<'a>,
        pub blackhole_mass_scale: wgpu::BufferBinding<'a>,
        pub blackhole_size_scale: wgpu::BufferBinding<'a>,
        pub blackholes: wgpu::BufferBinding<'a>,
    }
    #[derive(Clone, Debug)]
    pub struct WgpuBindGroup1Entries<'a> {
        pub blackhole_count: wgpu::BindGroupEntry<'a>,
        pub blackhole_mass_scale: wgpu::BindGroupEntry<'a>,
        pub blackhole_size_scale: wgpu::BindGroupEntry<'a>,
        pub blackholes: wgpu::BindGroupEntry<'a>,
    }
    impl<'a> WgpuBindGroup1Entries<'a> {
        pub fn new(params: WgpuBindGroup1EntriesParams<'a>) -> Self {
            Self {
                blackhole_count: wgpu::BindGroupEntry {
                    binding: 0,
                    resource: wgpu::BindingResource::Buffer(params.blackhole_count),
                },
                blackhole_mass_scale: wgpu::BindGroupEntry {
                    binding: 1,
                    resource: wgpu::BindingResource::Buffer(params.blackhole_mass_scale),
                },
                blackhole_size_scale: wgpu::BindGroupEntry {
                    binding: 2,
                    resource: wgpu::BindingResource::Buffer(params.blackhole_size_scale),
                },
                blackholes: wgpu::BindGroupEntry {
                    binding: 3,
                    resource: wgpu::BindingResource::Buffer(params.blackholes),
                },
            }
        }
        pub fn into_array(self) -> [wgpu::BindGroupEntry<'a>; 4] {
            [
                self.blackhole_count,
                self.blackhole_mass_scale,
                self.blackhole_size_scale,
                self.blackholes,
            ]
        }
        pub fn collect<B: FromIterator<wgpu::BindGroupEntry<'a>>>(self) -> B {
            self.into_array().into_iter().collect()
        }
    }
    #[derive(Debug)]
    pub struct WgpuBindGroup1(wgpu::BindGroup);
    impl WgpuBindGroup1 {
        pub const LAYOUT_DESCRIPTOR: wgpu::BindGroupLayoutDescriptor<'static> = wgpu::BindGroupLayoutDescriptor {
            label: Some("Integration::BindGroup1::LayoutDescriptor"),
            entries: &[
                #[doc = " @binding(0): \"blackhole_count\""]
                wgpu::BindGroupLayoutEntry {
                    binding: 0,
                    visibility: wgpu::ShaderStages::COMPUTE,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Uniform,
                        has_dynamic_offset: false,
                        min_binding_size: std::num::NonZeroU64::new(std::mem::size_of::<u32>() as _),
                    },
                    count: None,
                },
                #[doc = " @binding(1): \"blackhole_mass_scale\""]
                wgpu::BindGroupLayoutEntry {
                    binding: 1,
                    visibility: wgpu::ShaderStages::COMPUTE,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Uniform,
                        has_dynamic_offset: false,
                        min_binding_size: std::num::NonZeroU64::new(std::mem::size_of::<f32>() as _),
                    },
                    count: None,
                },
                #[doc = " @binding(2): \"blackhole_size_scale\""]
                wgpu::BindGroupLayoutEntry {
                    binding: 2,
                    visibility: wgpu::ShaderStages::COMPUTE,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Uniform,
                        has_dynamic_offset: false,
                        min_binding_size: std::num::NonZeroU64::new(std::mem::size_of::<f32>() as _),
                    },
                    count: None,
                },
                #[doc = " @binding(3): \"blackholes\""]
                wgpu::BindGroupLayoutEntry {
                    binding: 3,
                    visibility: wgpu::ShaderStages::COMPUTE,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Storage { read_only: true },
                        has_dynamic_offset: false,
                        min_binding_size: None,
                    },
                    count: None,
                },
            ],
        };
        pub fn get_bind_group_layout(device: &wgpu::Device) -> wgpu::BindGroupLayout {
            device.create_bind_group_layout(&Self::LAYOUT_DESCRIPTOR)
        }
        pub fn from_bindings(device: &wgpu::Device, bindings: WgpuBindGroup1Entries) -> Self {
            let bind_group_layout = Self::get_bind_group_layout(device);
            let entries = bindings.into_array();
            let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
                label: Some("Integration::BindGroup1"),
                layout: &bind_group_layout,
                entries: &entries,
            });
            Self(bind_group)
        }
        pub fn set(&self, pass: &mut impl SetBindGroup) {
            pass.set_bind_group(1, &self.0, &[]);
        }
    }
    #[derive(Debug)]
    pub struct WgpuBindGroup2EntriesParams<'a> {
        pub flags: wgpu::BufferBinding<'a>,
        pub aabbs: wgpu::BufferBinding<'a>,
        pub velocities: wgpu::BufferBinding<'a>,
        pub integrated_flags: wgpu::BufferBinding<'a>,
        pub integrated_aabbs: wgpu::BufferBinding<'a>,
        pub integrated_velocities: wgpu::BufferBinding<'a>,
    }
    #[derive(Clone, Debug)]
    pub struct WgpuBindGroup2Entries<'a> {
        pub flags: wgpu::BindGroupEntry<'a>,
        pub aabbs: wgpu::BindGroupEntry<'a>,
        pub velocities: wgpu::BindGroupEntry<'a>,
        pub integrated_flags: wgpu::BindGroupEntry<'a>,
        pub integrated_aabbs: wgpu::BindGroupEntry<'a>,
        pub integrated_velocities: wgpu::BindGroupEntry<'a>,
    }
    impl<'a> WgpuBindGroup2Entries<'a> {
        pub fn new(params: WgpuBindGroup2EntriesParams<'a>) -> Self {
            Self {
                flags: wgpu::BindGroupEntry {
                    binding: 0,
                    resource: wgpu::BindingResource::Buffer(params.flags),
                },
                aabbs: wgpu::BindGroupEntry {
                    binding: 1,
                    resource: wgpu::BindingResource::Buffer(params.aabbs),
                },
                velocities: wgpu::BindGroupEntry {
                    binding: 2,
                    resource: wgpu::BindingResource::Buffer(params.velocities),
                },
                integrated_flags: wgpu::BindGroupEntry {
                    binding: 3,
                    resource: wgpu::BindingResource::Buffer(params.integrated_flags),
                },
                integrated_aabbs: wgpu::BindGroupEntry {
                    binding: 4,
                    resource: wgpu::BindingResource::Buffer(params.integrated_aabbs),
                },
                integrated_velocities: wgpu::BindGroupEntry {
                    binding: 5,
                    resource: wgpu::BindingResource::Buffer(params.integrated_velocities),
                },
            }
        }
        pub fn into_array(self) -> [wgpu::BindGroupEntry<'a>; 6] {
            [
                self.flags,
                self.aabbs,
                self.velocities,
                self.integrated_flags,
                self.integrated_aabbs,
                self.integrated_velocities,
            ]
        }
        pub fn collect<B: FromIterator<wgpu::BindGroupEntry<'a>>>(self) -> B {
            self.into_array().into_iter().collect()
        }
    }
    #[derive(Debug)]
    pub struct WgpuBindGroup2(wgpu::BindGroup);
    impl WgpuBindGroup2 {
        pub const LAYOUT_DESCRIPTOR: wgpu::BindGroupLayoutDescriptor<'static> = wgpu::BindGroupLayoutDescriptor {
            label: Some("Integration::BindGroup2::LayoutDescriptor"),
            entries: &[
                #[doc = " @binding(0): \"flags\""]
                wgpu::BindGroupLayoutEntry {
                    binding: 0,
                    visibility: wgpu::ShaderStages::COMPUTE,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Storage { read_only: true },
                        has_dynamic_offset: false,
                        min_binding_size: None,
                    },
                    count: None,
                },
                #[doc = " @binding(1): \"aabbs\""]
                wgpu::BindGroupLayoutEntry {
                    binding: 1,
                    visibility: wgpu::ShaderStages::COMPUTE,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Storage { read_only: true },
                        has_dynamic_offset: false,
                        min_binding_size: None,
                    },
                    count: None,
                },
                #[doc = " @binding(2): \"velocities\""]
                wgpu::BindGroupLayoutEntry {
                    binding: 2,
                    visibility: wgpu::ShaderStages::COMPUTE,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Storage { read_only: true },
                        has_dynamic_offset: false,
                        min_binding_size: None,
                    },
                    count: None,
                },
                #[doc = " @binding(3): \"integrated_flags\""]
                wgpu::BindGroupLayoutEntry {
                    binding: 3,
                    visibility: wgpu::ShaderStages::COMPUTE,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Storage { read_only: false },
                        has_dynamic_offset: false,
                        min_binding_size: None,
                    },
                    count: None,
                },
                #[doc = " @binding(4): \"integrated_aabbs\""]
                wgpu::BindGroupLayoutEntry {
                    binding: 4,
                    visibility: wgpu::ShaderStages::COMPUTE,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Storage { read_only: false },
                        has_dynamic_offset: false,
                        min_binding_size: None,
                    },
                    count: None,
                },
                #[doc = " @binding(5): \"integrated_velocities\""]
                wgpu::BindGroupLayoutEntry {
                    binding: 5,
                    visibility: wgpu::ShaderStages::COMPUTE,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Storage { read_only: false },
                        has_dynamic_offset: false,
                        min_binding_size: None,
                    },
                    count: None,
                },
            ],
        };
        pub fn get_bind_group_layout(device: &wgpu::Device) -> wgpu::BindGroupLayout {
            device.create_bind_group_layout(&Self::LAYOUT_DESCRIPTOR)
        }
        pub fn from_bindings(device: &wgpu::Device, bindings: WgpuBindGroup2Entries) -> Self {
            let bind_group_layout = Self::get_bind_group_layout(device);
            let entries = bindings.into_array();
            let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
                label: Some("Integration::BindGroup2"),
                layout: &bind_group_layout,
                entries: &entries,
            });
            Self(bind_group)
        }
        pub fn set(&self, pass: &mut impl SetBindGroup) {
            pass.set_bind_group(2, &self.0, &[]);
        }
    }
    #[doc = " Bind groups can be set individually using their set(render_pass) method, or all at once using `WgpuBindGroups::set`."]
    #[doc = " For optimal performance with many draw calls, it's recommended to organize bindings into bind groups based on update frequency:"]
    #[doc = "   - Bind group 0: Least frequent updates (e.g. per frame resources)"]
    #[doc = "   - Bind group 1: More frequent updates"]
    #[doc = "   - Bind group 2: More frequent updates"]
    #[doc = "   - Bind group 3: Most frequent updates (e.g. per draw resources)"]
    #[derive(Debug, Copy, Clone)]
    pub struct WgpuBindGroups<'a> {
        pub bind_group0: &'a WgpuBindGroup0,
        pub bind_group1: &'a WgpuBindGroup1,
        pub bind_group2: &'a WgpuBindGroup2,
    }
    impl<'a> WgpuBindGroups<'a> {
        pub fn set(&self, pass: &mut impl SetBindGroup) {
            self.bind_group0.set(pass);
            self.bind_group1.set(pass);
            self.bind_group2.set(pass);
        }
    }
    #[derive(Debug)]
    pub struct WgpuPipelineLayout;
    impl WgpuPipelineLayout {
        pub fn bind_group_layout_entries(entries: [wgpu::BindGroupLayout; 3]) -> [wgpu::BindGroupLayout; 3] {
            entries
        }
    }
    pub fn create_pipeline_layout(device: &wgpu::Device) -> wgpu::PipelineLayout {
        device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("Integration::PipelineLayout"),
            bind_group_layouts: &[
                &WgpuBindGroup0::get_bind_group_layout(device),
                &WgpuBindGroup1::get_bind_group_layout(device),
                &WgpuBindGroup2::get_bind_group_layout(device),
            ],
            push_constant_ranges: &[],
        })
    }
    pub fn create_shader_module_embed_source(device: &wgpu::Device) -> wgpu::ShaderModule {
        let source = std::borrow::Cow::Borrowed(SHADER_STRING);
        device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("integration.wgsl"),
            source: wgpu::ShaderSource::Wgsl(source),
        })
    }
    pub const SHADER_STRING: &str = r#"
struct VelocityX_naga_oil_mod_XMNXW23LPNYX {
    inner: vec2<f32>,
}

struct MassX_naga_oil_mod_XMNXW23LPNYX {
    inner: f32,
}

struct FlagsX_naga_oil_mod_XMNXW23LPNYX {
    inner: u32,
}

struct AABBX_naga_oil_mod_XMNXW23LPNYX {
    min: vec2<f32>,
    max: vec2<f32>,
}

struct BvhNodeX_naga_oil_mod_XMNXW23LPNYX {
    index: u32,
}

struct BlackHole {
    position: vec2<f32>,
    radius: f32,
    mass: f32,
    spin: f32,
}

struct ObjectPhaseState {
    position: vec2<f32>,
    velocity: vec2<f32>,
}

struct InteractionResult {
    force: vec2<f32>,
    collision_count: u32,
}

const FLAG_DRAW_OBJECTX_naga_oil_mod_XMNXW23LPNYX: u32 = 1u;
const FLAG_DRAW_AABBX_naga_oil_mod_XMNXW23LPNYX: u32 = 2u;
const FLAG_PHYSICALX_naga_oil_mod_XMNXW23LPNYX: u32 = 4u;
const BVH_NODE_TREE_FLAGX_naga_oil_mod_XMNXW23LPNYX: u32 = 2147483648u;
const WORKGROUP_SIZE: u32 = 64u;
const STIFFNESS: f32 = 1000000f;
const RESTITUTION: f32 = 0.85f;
const GAMMA_COEFF: f32 = 186.15263f;

@group(0) @binding(0) 
var<uniform> dt: f32;
@group(0) @binding(1) 
var<uniform> gravitational_constant: f32;
@group(0) @binding(2) 
var<uniform> global_force: vec2<f32>;
@group(0) @binding(3) 
var<storage> masses: array<MassX_naga_oil_mod_XMNXW23LPNYX>;
@group(0) @binding(4) 
var<storage> nodes: array<BvhNodeX_naga_oil_mod_XMNXW23LPNYX>;
@group(1) @binding(0) 
var<uniform> blackhole_count: u32;
@group(1) @binding(1) 
var<uniform> blackhole_mass_scale: f32;
@group(1) @binding(2) 
var<uniform> blackhole_size_scale: f32;
@group(1) @binding(3) 
var<storage> blackholes: array<BlackHole>;
@group(2) @binding(0) 
var<storage> flags: array<FlagsX_naga_oil_mod_XMNXW23LPNYX>;
@group(2) @binding(1) 
var<storage> aabbs: array<AABBX_naga_oil_mod_XMNXW23LPNYX>;
@group(2) @binding(2) 
var<storage> velocities: array<VelocityX_naga_oil_mod_XMNXW23LPNYX>;
@group(2) @binding(3) 
var<storage, read_write> integrated_flags: array<FlagsX_naga_oil_mod_XMNXW23LPNYX>;
@group(2) @binding(4) 
var<storage, read_write> integrated_aabbs: array<AABBX_naga_oil_mod_XMNXW23LPNYX>;
@group(2) @binding(5) 
var<storage, read_write> integrated_velocities: array<VelocityX_naga_oil_mod_XMNXW23LPNYX>;

fn invocation_indexX_naga_oil_mod_XMNXW23LPNYX(gid_1: vec3<u32>, nwg_1: vec3<u32>, workgroup_size: u32) -> u32 {
    return (gid_1.x + ((gid_1.y * nwg_1.x) * workgroup_size));
}

fn blackhole_gravity(blackhole: BlackHole, position: vec2<f32>, mass: f32) -> vec2<f32> {
    let to_blackhole = (blackhole.position - position);
    let direction = normalize(to_blackhole);
    let distance = length(to_blackhole);
    let _e8 = gravitational_constant;
    let _e14 = blackhole_mass_scale;
    return (((((direction * _e8) * mass) * blackhole.mass) * _e14) / vec2((distance * distance)));
}

fn frame_dragging(blackhole_1: BlackHole, state_1: ObjectPhaseState) -> vec2<f32> {
    let r_vec = (blackhole_1.position - state_1.position);
    let r = length(r_vec);
    let J = blackhole_1.spin;
    let v_perp = vec2<f32>(-(state_1.velocity.y), state_1.velocity.x);
    let _e14 = gravitational_constant;
    return ((((2f * _e14) * J) / pow(r, 3f)) * v_perp);
}

fn aabb_overlaps(a: AABBX_naga_oil_mod_XMNXW23LPNYX, b: AABBX_naga_oil_mod_XMNXW23LPNYX) -> bool {
    return ((((a.min.x < b.max.x) && (a.max.x > b.min.x)) && (a.min.y < b.max.y)) && (a.max.y > b.min.y));
}

fn collision_repulsion_pair(aabb: AABBX_naga_oil_mod_XMNXW23LPNYX, other_aabb: AABBX_naga_oil_mod_XMNXW23LPNYX, velocity: vec2<f32>, mass_1: f32, other_index: u32) -> vec2<f32> {
    var v_ij_n: f32;
    var f_damping: vec2<f32> = vec2<f32>();

    let size = (aabb.max - aabb.min);
    let other_size = (other_aabb.max - other_aabb.min);
    let position_1 = ((aabb.min + aabb.max) / vec2(2f));
    let other_position = ((other_aabb.min + other_aabb.max) / vec2(2f));
    let separation_vector = (position_1 - other_position);
    let distance_1 = length(separation_vector);
    let r1_ = (0.5f * size.x);
    let r2_ = (0.5f * other_size.x);
    let interaction_distance = (r1_ + r2_);
    if (distance_1 >= interaction_distance) {
        return vec2<f32>();
    }
    let penetration = (interaction_distance - distance_1);
    let n = normalize(separation_vector);
    let _e39 = velocities[other_index].inner;
    v_ij_n = dot((velocity - _e39), n);
    let _e45 = v_ij_n;
    if ((penetration <= 0f) && (_e45 > 0f)) {
        let _e50 = v_ij_n;
        v_ij_n = (-0.85f * _e50);
    }
    let m2_ = masses[other_index].inner;
    let m_eff = ((mass_1 * m2_) / (mass_1 + m2_));
    let _e60 = v_ij_n;
    if (_e60 < 0f) {
        let _e66 = v_ij_n;
        f_damping = (((-186.15263f * sqrt(m_eff)) * _e66) * n);
    }
    let f_elastic = ((STIFFNESS * penetration) * n);
    let _e73 = f_damping;
    return (f_elastic + _e73);
}

fn collision_repulsion(index: u32, aabb_1: AABBX_naga_oil_mod_XMNXW23LPNYX, velocity_1: vec2<f32>, mass_2: f32) -> vec2<f32> {
    var stack: array<u32, 64>;
    var sp: u32 = 0u;
    var total_force: vec2<f32> = vec2<f32>();

    let _e4 = sp;
    stack[_e4] = (arrayLength((&nodes)) - 1u);
    let _e11 = sp;
    sp = (_e11 + 1u);
    loop {
        let _e13 = sp;
        if (_e13 > 0u) {
        } else {
            break;
        }
        {
            let _e16 = sp;
            let node_index = stack[(_e16 - 1u)];
            let _e22 = sp;
            sp = (_e22 - 1u);
            let other_index_1 = nodes[node_index].index;
            if ((other_index_1 & BVH_NODE_TREE_FLAGX_naga_oil_mod_XMNXW23LPNYX) != 0u) {
                let _e32 = sp;
                if (_e32 >= 62u) {
                    break;
                }
                let i = (other_index_1 & 2147483647u);
                let _e37 = sp;
                stack[_e37] = i;
                let _e39 = sp;
                stack[(_e39 + 1u)] = (i + 1u);
                let _e46 = sp;
                sp = (_e46 + 2u);
            } else {
                let _e53 = flags[other_index_1].inner;
                if ((other_index_1 != index) && ((_e53 & FLAG_PHYSICALX_naga_oil_mod_XMNXW23LPNYX) != 0u)) {
                    let other_aabb_1 = aabbs[other_index_1];
                    let _e63 = aabb_overlaps(aabb_1, other_aabb_1);
                    if _e63 {
                        let _e66 = collision_repulsion_pair(aabb_1, other_aabb_1, velocity_1, mass_2, other_index_1);
                        let _e68 = total_force;
                        total_force = (_e68 + _e66);
                    }
                }
            }
        }
    }
    let _e70 = total_force;
    return _e70;
}

fn forces(state_2: ObjectPhaseState, index_1: u32, aabb_2: AABBX_naga_oil_mod_XMNXW23LPNYX, mass_3: f32) -> vec2<f32> {
    var total_force_1: vec2<f32>;
    var bh_index_1: u32 = 0u;
    var blackhole_2: BlackHole;

    let _e2 = global_force;
    total_force_1 = _e2;
    loop {
        let _e5 = bh_index_1;
        let _e7 = blackhole_count;
        if (_e5 < _e7) {
        } else {
            break;
        }
        {
            let _e10 = bh_index_1;
            let _e12 = blackholes[_e10];
            blackhole_2 = _e12;
            let _e15 = blackhole_2;
            let _e18 = blackhole_gravity(_e15, state_2.position, mass_3);
            let _e19 = total_force_1;
            total_force_1 = (_e19 + _e18);
            let _e21 = blackhole_2;
            let _e22 = frame_dragging(_e21, state_2);
            let _e23 = total_force_1;
            total_force_1 = (_e23 + _e22);
        }
        continuing {
            let _e26 = bh_index_1;
            bh_index_1 = (_e26 + 1u);
        }
    }
    let _e31 = collision_repulsion(index_1, aabb_2, state_2.velocity, mass_3);
    let _e32 = total_force_1;
    total_force_1 = (_e32 + _e31);
    let _e34 = total_force_1;
    return _e34;
}

fn integrate_euler_symplectic(state_3: ObjectPhaseState, index_2: u32, aabb_3: AABBX_naga_oil_mod_XMNXW23LPNYX, mass_4: f32) -> ObjectPhaseState {
    var new_state: ObjectPhaseState;

    let _e4 = forces(state_3, index_2, aabb_3, mass_4);
    let a_1 = (_e4 / vec2(mass_4));
    new_state = state_3;
    let _e10 = dt;
    let _e12 = new_state.velocity;
    new_state.velocity = (_e12 + (a_1 * _e10));
    let _e16 = new_state.velocity;
    let _e18 = dt;
    let _e20 = new_state.position;
    new_state.position = (_e20 + (_e16 * _e18));
    let _e22 = new_state;
    return _e22;
}

@compute @workgroup_size(64, 1, 1) 
fn integrate(@builtin(global_invocation_id) gid: vec3<u32>, @builtin(num_workgroups) nwg: vec3<u32>) {
    var f: u32;
    var state: ObjectPhaseState;
    var bh_index: u32 = 0u;
    var new_aabb: AABBX_naga_oil_mod_XMNXW23LPNYX;

    let _e4 = invocation_indexX_naga_oil_mod_XMNXW23LPNYX(gid, nwg, WORKGROUP_SIZE);
    if (_e4 >= arrayLength((&masses))) {
        return;
    }
    let aabb_4 = aabbs[_e4];
    let initial_position = ((aabb_4.min + aabb_4.max) / vec2(2f));
    let initial_velocity = velocities[_e4].inner;
    let _e24 = flags[_e4].inner;
    f = _e24;
    let mass_5 = masses[_e4].inner;
    let _e33 = velocities[_e4].inner;
    state = ObjectPhaseState(initial_position, _e33);
    let _e36 = f;
    if ((_e36 & FLAG_PHYSICALX_naga_oil_mod_XMNXW23LPNYX) != 0u) {
        let _e41 = state;
        let _e42 = integrate_euler_symplectic(_e41, _e4, aabb_4, mass_5);
        state = _e42;
    }
    let size_1 = (aabb_4.max - aabb_4.min);
    loop {
        let _e47 = bh_index;
        let _e49 = blackhole_count;
        let _e51 = f;
        if ((_e47 < _e49) && ((_e51 & FLAG_PHYSICALX_naga_oil_mod_XMNXW23LPNYX) != 0u)) {
        } else {
            break;
        }
        {
            let _e58 = bh_index;
            let blackhole_3 = blackholes[_e58];
            let _e63 = state.position;
            let distance_2 = (length((blackhole_3.position - _e63)) - (max(size_1.x, size_1.y) / 2f));
            let _e74 = blackhole_size_scale;
            if (distance_2 < (blackhole_3.radius * _e74)) {
                let _e78 = f;
                f = (_e78 & 4294967288u);
                state.velocity = vec2<f32>();
            }
        }
        continuing {
            let _e83 = bh_index;
            bh_index = (_e83 + 1u);
        }
    }
    let _e86 = state.position;
    let offset = (_e86 - initial_position);
    new_aabb = AABBX_naga_oil_mod_XMNXW23LPNYX((aabb_4.min + offset), (aabb_4.max + offset));
    let _e96 = new_aabb.min.y;
    if (_e96 < -1000f) {
        let _e101 = new_aabb.min.y;
        let overshoot = (-1000f - _e101);
        let _e108 = new_aabb.min.y;
        new_aabb.min.y = (_e108 + (overshoot / 2f));
        let _e114 = new_aabb.max.y;
        new_aabb.max.y = (_e114 + (overshoot / 2f));
        let _e119 = state.velocity.y;
        state.velocity.y = (_e119 * -1f);
    }
    let _e123 = new_aabb.max.y;
    if (_e123 > 1000f) {
        let _e128 = new_aabb.max.y;
        let overshoot_1 = (_e128 - 1000f);
        let _e135 = new_aabb.min.y;
        new_aabb.min.y = (_e135 - (overshoot_1 / 2f));
        let _e141 = new_aabb.max.y;
        new_aabb.max.y = (_e141 - (overshoot_1 / 2f));
        let _e146 = state.velocity.y;
        state.velocity.y = (_e146 * -1f);
    }
    let _e150 = new_aabb.min.x;
    if (_e150 < -1600f) {
        let _e155 = new_aabb.min.x;
        let overshoot_2 = (-1600f - _e155);
        let _e162 = new_aabb.min.x;
        new_aabb.min.x = (_e162 + (overshoot_2 / 2f));
        let _e168 = new_aabb.max.x;
        new_aabb.max.x = (_e168 + (overshoot_2 / 2f));
        let _e173 = state.velocity.x;
        state.velocity.x = (_e173 * -1f);
    }
    let _e177 = new_aabb.max.x;
    if (_e177 > 1600f) {
        let _e182 = new_aabb.max.x;
        let overshoot_3 = (_e182 - 1600f);
        let _e189 = new_aabb.min.x;
        new_aabb.min.x = (_e189 - (overshoot_3 / 2f));
        let _e195 = new_aabb.max.x;
        new_aabb.max.x = (_e195 - (overshoot_3 / 2f));
        let _e200 = state.velocity.x;
        state.velocity.x = (_e200 * -1f);
    }
    let _e205 = f;
    integrated_flags[_e4].inner = _e205;
    let _e208 = new_aabb;
    integrated_aabbs[_e4] = _e208;
    let _e213 = state.velocity;
    integrated_velocities[_e4].inner = _e213;
    return;
}
"#;
}
