// File automatically generated by wgsl_bindgen^
//
// ^ wgsl_bindgen version 0.21.2
// Changes made to this file will not be saved.
// SourceHash: 1bfe586ec6ad2cf23a31c892ac6ca7e324b99e2d381032c0d5d36c647cc3c4e9

#![allow(unused, non_snake_case, non_camel_case_types, non_upper_case_globals)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ShaderEntry {
    Shape,
}
impl ShaderEntry {
    pub fn create_pipeline_layout(&self, device: &wgpu::Device) -> wgpu::PipelineLayout {
        match self {
            Self::Shape => shape::create_pipeline_layout(device),
        }
    }
    pub fn create_shader_module_embed_source(&self, device: &wgpu::Device) -> wgpu::ShaderModule {
        match self {
            Self::Shape => shape::create_shader_module_embed_source(device),
        }
    }
}
mod _root {
    pub use super::*;
    pub trait SetBindGroup {
        fn set_bind_group(&mut self, index: u32, bind_group: &wgpu::BindGroup, offsets: &[wgpu::DynamicOffset]);
    }
    impl SetBindGroup for wgpu::RenderPass<'_> {
        fn set_bind_group(&mut self, index: u32, bind_group: &wgpu::BindGroup, offsets: &[wgpu::DynamicOffset]) {
            self.set_bind_group(index, bind_group, offsets);
        }
    }
    impl SetBindGroup for wgpu::RenderBundleEncoder<'_> {
        fn set_bind_group(&mut self, index: u32, bind_group: &wgpu::BindGroup, offsets: &[wgpu::DynamicOffset]) {
            self.set_bind_group(index, bind_group, offsets);
        }
    }
}
pub mod layout_asserts {
    use super::{_root, _root::*};
    const WGSL_BASE_TYPE_ASSERTS: () = {};
    const SHAPE_UNIFORMS_ASSERTS: () = {
        assert!(std::mem::offset_of!(shape::Uniforms, view_size) == 0);
        assert!(std::mem::size_of::<shape::Uniforms>() == 8);
    };
}
pub mod shape {
    use super::{_root, _root::*};
    #[repr(C, align(8))]
    #[derive(Debug, PartialEq, Clone, Copy)]
    pub struct Uniforms {
        #[doc = "offset: 0, size: 8, type: `vec2<f32>`"]
        pub view_size: [f32; 2],
    }
    impl Uniforms {
        pub const fn new(view_size: [f32; 2]) -> Self {
            Self { view_size }
        }
    }
    #[repr(C)]
    #[derive(Debug, PartialEq, Clone, Copy)]
    pub struct VertexInput {
        pub inner: [f32; 2],
    }
    impl VertexInput {
        pub const fn new(inner: [f32; 2]) -> Self {
            Self { inner }
        }
    }
    impl VertexInput {
        pub const VERTEX_ATTRIBUTES: [wgpu::VertexAttribute; 1] = [wgpu::VertexAttribute {
            format: wgpu::VertexFormat::Float32x2,
            offset: std::mem::offset_of!(Self, inner) as u64,
            shader_location: 0,
        }];
        pub const fn vertex_buffer_layout(step_mode: wgpu::VertexStepMode) -> wgpu::VertexBufferLayout<'static> {
            wgpu::VertexBufferLayout {
                array_stride: std::mem::size_of::<Self>() as u64,
                step_mode,
                attributes: &Self::VERTEX_ATTRIBUTES,
            }
        }
    }
    #[repr(C)]
    #[derive(Debug, PartialEq, Clone, Copy)]
    pub struct FlagsInput {
        pub inner: u32,
    }
    impl FlagsInput {
        pub const fn new(inner: u32) -> Self {
            Self { inner }
        }
    }
    impl FlagsInput {
        pub const VERTEX_ATTRIBUTES: [wgpu::VertexAttribute; 1] = [wgpu::VertexAttribute {
            format: wgpu::VertexFormat::Uint32,
            offset: std::mem::offset_of!(Self, inner) as u64,
            shader_location: 1,
        }];
        pub const fn vertex_buffer_layout(step_mode: wgpu::VertexStepMode) -> wgpu::VertexBufferLayout<'static> {
            wgpu::VertexBufferLayout {
                array_stride: std::mem::size_of::<Self>() as u64,
                step_mode,
                attributes: &Self::VERTEX_ATTRIBUTES,
            }
        }
    }
    #[repr(C)]
    #[derive(Debug, PartialEq, Clone, Copy)]
    pub struct PositionInput {
        pub inner: [f32; 2],
    }
    impl PositionInput {
        pub const fn new(inner: [f32; 2]) -> Self {
            Self { inner }
        }
    }
    impl PositionInput {
        pub const VERTEX_ATTRIBUTES: [wgpu::VertexAttribute; 1] = [wgpu::VertexAttribute {
            format: wgpu::VertexFormat::Float32x2,
            offset: std::mem::offset_of!(Self, inner) as u64,
            shader_location: 2,
        }];
        pub const fn vertex_buffer_layout(step_mode: wgpu::VertexStepMode) -> wgpu::VertexBufferLayout<'static> {
            wgpu::VertexBufferLayout {
                array_stride: std::mem::size_of::<Self>() as u64,
                step_mode,
                attributes: &Self::VERTEX_ATTRIBUTES,
            }
        }
    }
    #[repr(C)]
    #[derive(Debug, PartialEq, Clone, Copy)]
    pub struct SizeInput {
        pub inner: [f32; 2],
    }
    impl SizeInput {
        pub const fn new(inner: [f32; 2]) -> Self {
            Self { inner }
        }
    }
    impl SizeInput {
        pub const VERTEX_ATTRIBUTES: [wgpu::VertexAttribute; 1] = [wgpu::VertexAttribute {
            format: wgpu::VertexFormat::Float32x2,
            offset: std::mem::offset_of!(Self, inner) as u64,
            shader_location: 3,
        }];
        pub const fn vertex_buffer_layout(step_mode: wgpu::VertexStepMode) -> wgpu::VertexBufferLayout<'static> {
            wgpu::VertexBufferLayout {
                array_stride: std::mem::size_of::<Self>() as u64,
                step_mode,
                attributes: &Self::VERTEX_ATTRIBUTES,
            }
        }
    }
    #[repr(C)]
    #[derive(Debug, PartialEq, Clone, Copy)]
    pub struct ColorInput {
        pub inner: [f32; 4],
    }
    impl ColorInput {
        pub const fn new(inner: [f32; 4]) -> Self {
            Self { inner }
        }
    }
    impl ColorInput {
        pub const VERTEX_ATTRIBUTES: [wgpu::VertexAttribute; 1] = [wgpu::VertexAttribute {
            format: wgpu::VertexFormat::Float32x4,
            offset: std::mem::offset_of!(Self, inner) as u64,
            shader_location: 4,
        }];
        pub const fn vertex_buffer_layout(step_mode: wgpu::VertexStepMode) -> wgpu::VertexBufferLayout<'static> {
            wgpu::VertexBufferLayout {
                array_stride: std::mem::size_of::<Self>() as u64,
                step_mode,
                attributes: &Self::VERTEX_ATTRIBUTES,
            }
        }
    }
    #[repr(C)]
    #[derive(Debug, PartialEq, Clone, Copy)]
    pub struct ShapeInput {
        pub inner: u32,
    }
    impl ShapeInput {
        pub const fn new(inner: u32) -> Self {
            Self { inner }
        }
    }
    impl ShapeInput {
        pub const VERTEX_ATTRIBUTES: [wgpu::VertexAttribute; 1] = [wgpu::VertexAttribute {
            format: wgpu::VertexFormat::Uint32,
            offset: std::mem::offset_of!(Self, inner) as u64,
            shader_location: 5,
        }];
        pub const fn vertex_buffer_layout(step_mode: wgpu::VertexStepMode) -> wgpu::VertexBufferLayout<'static> {
            wgpu::VertexBufferLayout {
                array_stride: std::mem::size_of::<Self>() as u64,
                step_mode,
                attributes: &Self::VERTEX_ATTRIBUTES,
            }
        }
    }
    pub const SHAPE_RECT: u32 = 0u32;
    pub const SHAPE_CIRCLE: u32 = 1u32;
    pub const FLAG_SHOW: u32 = 1u32;
    pub const ENTRY_VS_MAIN: &str = "vs_main";
    pub const ENTRY_FS_MAIN: &str = "fs_main";
    #[derive(Debug)]
    pub struct VertexEntry<const N: usize> {
        pub entry_point: &'static str,
        pub buffers: [wgpu::VertexBufferLayout<'static>; N],
        pub constants: Vec<(&'static str, f64)>,
    }
    pub fn vertex_state<'a, const N: usize>(
        module: &'a wgpu::ShaderModule,
        entry: &'a VertexEntry<N>,
    ) -> wgpu::VertexState<'a> {
        wgpu::VertexState {
            module,
            entry_point: Some(entry.entry_point),
            buffers: &entry.buffers,
            compilation_options: wgpu::PipelineCompilationOptions {
                constants: &entry.constants,
                ..Default::default()
            },
        }
    }
    pub fn vs_main_entry(
        vertex_input: wgpu::VertexStepMode,
        flags_input: wgpu::VertexStepMode,
        position_input: wgpu::VertexStepMode,
        size_input: wgpu::VertexStepMode,
        color_input: wgpu::VertexStepMode,
        shape_input: wgpu::VertexStepMode,
    ) -> VertexEntry<6> {
        VertexEntry {
            entry_point: ENTRY_VS_MAIN,
            buffers: [
                VertexInput::vertex_buffer_layout(vertex_input),
                FlagsInput::vertex_buffer_layout(flags_input),
                PositionInput::vertex_buffer_layout(position_input),
                SizeInput::vertex_buffer_layout(size_input),
                ColorInput::vertex_buffer_layout(color_input),
                ShapeInput::vertex_buffer_layout(shape_input),
            ],
            constants: Default::default(),
        }
    }
    #[derive(Debug)]
    pub struct FragmentEntry<const N: usize> {
        pub entry_point: &'static str,
        pub targets: [Option<wgpu::ColorTargetState>; N],
        pub constants: Vec<(&'static str, f64)>,
    }
    pub fn fragment_state<'a, const N: usize>(
        module: &'a wgpu::ShaderModule,
        entry: &'a FragmentEntry<N>,
    ) -> wgpu::FragmentState<'a> {
        wgpu::FragmentState {
            module,
            entry_point: Some(entry.entry_point),
            targets: &entry.targets,
            compilation_options: wgpu::PipelineCompilationOptions {
                constants: &entry.constants,
                ..Default::default()
            },
        }
    }
    pub fn fs_main_entry(targets: [Option<wgpu::ColorTargetState>; 1]) -> FragmentEntry<1> {
        FragmentEntry {
            entry_point: ENTRY_FS_MAIN,
            targets,
            constants: Default::default(),
        }
    }
    #[derive(Debug)]
    pub struct WgpuBindGroup0EntriesParams<'a> {
        pub uniforms: wgpu::BufferBinding<'a>,
    }
    #[derive(Clone, Debug)]
    pub struct WgpuBindGroup0Entries<'a> {
        pub uniforms: wgpu::BindGroupEntry<'a>,
    }
    impl<'a> WgpuBindGroup0Entries<'a> {
        pub fn new(params: WgpuBindGroup0EntriesParams<'a>) -> Self {
            Self {
                uniforms: wgpu::BindGroupEntry {
                    binding: 0,
                    resource: wgpu::BindingResource::Buffer(params.uniforms),
                },
            }
        }
        pub fn into_array(self) -> [wgpu::BindGroupEntry<'a>; 1] {
            [self.uniforms]
        }
        pub fn collect<B: FromIterator<wgpu::BindGroupEntry<'a>>>(self) -> B {
            self.into_array().into_iter().collect()
        }
    }
    #[derive(Debug)]
    pub struct WgpuBindGroup0(wgpu::BindGroup);
    impl WgpuBindGroup0 {
        pub const LAYOUT_DESCRIPTOR: wgpu::BindGroupLayoutDescriptor<'static> = wgpu::BindGroupLayoutDescriptor {
            label: Some("Shape::BindGroup0::LayoutDescriptor"),
            entries: &[
                #[doc = " @binding(0): \"uniforms\""]
                wgpu::BindGroupLayoutEntry {
                    binding: 0,
                    visibility: wgpu::ShaderStages::VERTEX_FRAGMENT,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Uniform,
                        has_dynamic_offset: false,
                        min_binding_size: std::num::NonZeroU64::new(std::mem::size_of::<_root::shape::Uniforms>() as _),
                    },
                    count: None,
                },
            ],
        };
        pub fn get_bind_group_layout(device: &wgpu::Device) -> wgpu::BindGroupLayout {
            device.create_bind_group_layout(&Self::LAYOUT_DESCRIPTOR)
        }
        pub fn from_bindings(device: &wgpu::Device, bindings: WgpuBindGroup0Entries) -> Self {
            let bind_group_layout = Self::get_bind_group_layout(device);
            let entries = bindings.into_array();
            let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
                label: Some("Shape::BindGroup0"),
                layout: &bind_group_layout,
                entries: &entries,
            });
            Self(bind_group)
        }
        pub fn set(&self, pass: &mut impl SetBindGroup) {
            pass.set_bind_group(0, &self.0, &[]);
        }
    }
    #[doc = " Bind groups can be set individually using their set(render_pass) method, or all at once using `WgpuBindGroups::set`."]
    #[doc = " For optimal performance with many draw calls, it's recommended to organize bindings into bind groups based on update frequency:"]
    #[doc = "   - Bind group 0: Least frequent updates (e.g. per frame resources)"]
    #[doc = "   - Bind group 1: More frequent updates"]
    #[doc = "   - Bind group 2: More frequent updates"]
    #[doc = "   - Bind group 3: Most frequent updates (e.g. per draw resources)"]
    #[derive(Debug, Copy, Clone)]
    pub struct WgpuBindGroups<'a> {
        pub bind_group0: &'a WgpuBindGroup0,
    }
    impl<'a> WgpuBindGroups<'a> {
        pub fn set(&self, pass: &mut impl SetBindGroup) {
            self.bind_group0.set(pass);
        }
    }
    #[derive(Debug)]
    pub struct WgpuPipelineLayout;
    impl WgpuPipelineLayout {
        pub fn bind_group_layout_entries(entries: [wgpu::BindGroupLayout; 1]) -> [wgpu::BindGroupLayout; 1] {
            entries
        }
    }
    pub fn create_pipeline_layout(device: &wgpu::Device) -> wgpu::PipelineLayout {
        device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("Shape::PipelineLayout"),
            bind_group_layouts: &[&WgpuBindGroup0::get_bind_group_layout(device)],
            push_constant_ranges: &[],
        })
    }
    pub fn create_shader_module_embed_source(device: &wgpu::Device) -> wgpu::ShaderModule {
        let source = std::borrow::Cow::Borrowed(SHADER_STRING);
        device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("shape.wgsl"),
            source: wgpu::ShaderSource::Wgsl(source),
        })
    }
    pub const SHADER_STRING: &str = r#"
struct Uniforms {
    view_size: vec2<f32>,
}

struct VertexInput {
    @location(0) inner: vec2<f32>,
}

struct FlagsInput {
    @location(1) @interpolate(flat) inner: u32,
}

struct PositionInput {
    @location(2) inner: vec2<f32>,
}

struct SizeInput {
    @location(3) inner: vec2<f32>,
}

struct ColorInput {
    @location(4) inner: vec4<f32>,
}

struct ShapeInput {
    @location(5) @interpolate(flat) inner: u32,
}

struct VertexOutput {
    @builtin(position) clip_position: vec4<f32>,
    @location(0) scaling_factor: f32,
    @location(1) quad_position: vec2<f32>,
    @location(2) color: vec4<f32>,
    @location(3) @interpolate(flat) shape: u32,
}

struct FragmentOutput {
    @location(0) color: vec4<f32>,
}

const SHAPE_RECT: u32 = 0u;
const SHAPE_CIRCLE: u32 = 1u;
const FLAG_SHOW: u32 = 1u;

@group(0) @binding(0) 
var<uniform> uniforms: Uniforms;

@vertex 
fn vs_main(vertex: VertexInput, flag: FlagsInput, position: PositionInput, size: SizeInput, color: ColorInput, shape: ShapeInput) -> VertexOutput {
    var out: VertexOutput;

    if ((flag.inner & FLAG_SHOW) == 0u) {
        let _e7 = out;
        return _e7;
    }
    let _e12 = uniforms.view_size;
    let scale = (size.inner / _e12);
    out.scaling_factor = clamp(min(scale.x, scale.y), 0f, 1f);
    let _e25 = uniforms.view_size;
    let translation = ((((position.inner / _e25) * vec2<f32>(2f, -2f)) + vec2<f32>(-1f, 1f)) / scale);
    let translation_matrix = transpose(mat4x4<f32>(vec4<f32>(1f, 0f, 0f, translation.x), vec4<f32>(0f, 1f, 0f, translation.y), vec4<f32>(0f, 0f, 1f, 0f), vec4<f32>(0f, 0f, 0f, 1f)));
    let scale_matrix = mat4x4<f32>(vec4<f32>(scale.x, 0f, 0f, 0f), vec4<f32>(0f, scale.y, 0f, 0f), vec4<f32>(0f, 0f, 1f, 0f), vec4<f32>(0f, 0f, 0f, 1f));
    out.clip_position = ((scale_matrix * translation_matrix) * vec4<f32>(vertex.inner, 0f, 1f));
    out.quad_position = vertex.inner;
    out.color = color.inner;
    out.shape = shape.inner;
    let _e95 = out;
    return _e95;
}

@fragment 
fn fs_main(in: VertexOutput) -> FragmentOutput {
    var color_1: vec4<f32>;

    color_1 = in.color;
    if (in.shape == SHAPE_CIRCLE) {
        color_1.w = smoothstep(1f, (1f - clamp((0.002f / in.scaling_factor), 0.002f, 0.3f)), length(in.quad_position));
    }
    let _e19 = color_1;
    return FragmentOutput(_e19);
}
"#;
}
pub mod bytemuck_impls {
    use super::{_root, _root::*};
    unsafe impl bytemuck::Zeroable for shape::Uniforms {}
    unsafe impl bytemuck::Pod for shape::Uniforms {}
    unsafe impl bytemuck::Zeroable for shape::VertexInput {}
    unsafe impl bytemuck::Pod for shape::VertexInput {}
    unsafe impl bytemuck::Zeroable for shape::FlagsInput {}
    unsafe impl bytemuck::Pod for shape::FlagsInput {}
    unsafe impl bytemuck::Zeroable for shape::PositionInput {}
    unsafe impl bytemuck::Pod for shape::PositionInput {}
    unsafe impl bytemuck::Zeroable for shape::SizeInput {}
    unsafe impl bytemuck::Pod for shape::SizeInput {}
    unsafe impl bytemuck::Zeroable for shape::ColorInput {}
    unsafe impl bytemuck::Pod for shape::ColorInput {}
    unsafe impl bytemuck::Zeroable for shape::ShapeInput {}
    unsafe impl bytemuck::Pod for shape::ShapeInput {}
}
